-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 014: Özel Teklifler (Special Offers) MVP Schema
-- Date: 2026-03-16
-- Plan: docs/superpowers/plans/2026-03-16-ozel-teklifler-mvp.md
--
-- EXECUTION ORDER:
--   1. PRE-CHECK: candidate_brand_follows
--   2. Enums
--   3. Tables (dependency order)
--   4. Indexes (already inline with tables)
--   5. ALTER TABLE candidates (new columns)
--   6. Triggers
--   7. Helper Functions
--   8. RLS Policies
--   9. Audience + Cron Functions
--  10. Admin user seed
--
-- IMPORTANT: Run in Supabase SQL editor. Do NOT split — run as single transaction.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. PRE-CHECK: candidate_brand_follows
-- This table was created in P2 Markalar session via SQL editor but migration
-- file was never committed. profil-ui.js uses it (lines 2470, 2641, 2644).
-- If it already exists, this block is a no-op.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS candidate_brand_follows (
  id            uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  candidate_id  bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  brand_id      bigint NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  created_at    timestamptz DEFAULT now(),
  UNIQUE(candidate_id, brand_id)
);

CREATE INDEX IF NOT EXISTS idx_cbf_candidate ON candidate_brand_follows(candidate_id);
CREATE INDEX IF NOT EXISTS idx_cbf_brand ON candidate_brand_follows(brand_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- 1b. PRE-CHECK: brands.segment column
-- The brands table (migration 012) does NOT have a segment column.
-- Audience targeting requires it for segment-based filtering.
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE brands ADD COLUMN IF NOT EXISTS segment text;

-- RLS for candidate_brand_follows (safe to re-run — DROP IF EXISTS + CREATE)
ALTER TABLE candidate_brand_follows ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'candidate_brand_follows' AND policyname = 'cbf_candidate_own') THEN
    CREATE POLICY cbf_candidate_own ON candidate_brand_follows
      FOR ALL USING (candidate_id = get_my_candidate_id());
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'candidate_brand_follows' AND policyname = 'cbf_employer_read') THEN
    CREATE POLICY cbf_employer_read ON candidate_brand_follows
      FOR SELECT USING (is_employer());
  END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. ENUMS
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TYPE campaign_type AS ENUM ('offer', 'employer_branding', 'hiring_boost');
CREATE TYPE campaign_status AS ENUM ('draft', 'pending_review', 'approved', 'rejected', 'revision_needed', 'active', 'paused', 'ended', 'archived');
CREATE TYPE distribution_mode AS ENUM ('followers_only', 'followers_plus_similar', 'broad_discovery');
CREATE TYPE access_mode AS ENUM ('public_all', 'visible_redeemable_premium', 'premium_exclusive');
CREATE TYPE campaign_package AS ENUM ('basic', 'boost', 'premium');
CREATE TYPE payment_status AS ENUM ('none', 'authorized', 'captured', 'released', 'refunded');
CREATE TYPE review_action AS ENUM ('approve', 'reject', 'revision_needed', 'pause', 'resume', 'archive', 'feature');
CREATE TYPE inbox_message_type AS ENUM ('campaign', 'system', 'employer_dm');
CREATE TYPE inbox_message_status AS ENUM ('pending', 'delivered', 'read');
CREATE TYPE email_job_status AS ENUM ('queued', 'sent', 'delivered', 'opened', 'clicked', 'failed');

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. TABLES (dependency order: no-FK tables first, then FK-dependent)
-- ═══════════════════════════════════════════════════════════════════════════

-- 3a. admin_users — no FK to other new tables
CREATE TABLE admin_users (
  id              uuid PRIMARY KEY REFERENCES auth.users(id),
  role            text NOT NULL DEFAULT 'superadmin',
  display_name    text,
  created_at      timestamptz DEFAULT now(),
  created_by      uuid REFERENCES auth.users(id)
);

-- 3b. campaigns — references companies, brands, auth.users (all existing)
CREATE TABLE campaigns (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Ownership
  company_id      bigint NOT NULL REFERENCES companies(id),
  brand_id        bigint REFERENCES brands(id),
  created_by      uuid NOT NULL REFERENCES auth.users(id),

  -- Content
  campaign_type   campaign_type NOT NULL,
  title           text NOT NULL,
  short_desc      text NOT NULL,
  full_desc       text,
  cta_label       text NOT NULL DEFAULT 'Detayları Gör',
  cta_url         text,
  promo_code      text,

  -- Assets
  cover_image_url text,
  logo_url        text,

  -- Targeting
  distribution_mode distribution_mode NOT NULL DEFAULT 'followers_only',
  access_mode     access_mode NOT NULL DEFAULT 'public_all',
  target_cities   text[],
  target_segments text[],
  target_seniority text[],
  target_tags     text[],

  -- Schedule
  start_date      timestamptz,
  end_date        timestamptz,
  CONSTRAINT campaigns_end_date_required CHECK (status = 'draft' OR end_date IS NOT NULL),

  -- Package & Delivery
  package         campaign_package NOT NULL DEFAULT 'basic',
  delivery_channels text[] NOT NULL DEFAULT '{feed}',

  -- Status
  status          campaign_status NOT NULL DEFAULT 'draft',

  -- Payment
  payment_status  payment_status NOT NULL DEFAULT 'none',
  payment_amount  integer,
  payment_currency text DEFAULT 'TRY',
  payment_provider text DEFAULT 'iyzico',
  payment_auth_id text,
  payment_capture_id text,

  -- Moderation
  moderation_flags text[],
  moderation_score integer DEFAULT 0,
  is_featured     boolean DEFAULT false,

  -- Metrics (denormalized)
  impression_count integer DEFAULT 0,
  click_count     integer DEFAULT 0,
  redeem_count    integer DEFAULT 0,

  -- Timestamps
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now(),
  submitted_at    timestamptz,
  approved_at     timestamptz,
  published_at    timestamptz,
  ended_at        timestamptz,
  archived_at     timestamptz,

  -- Relaunch
  parent_campaign_id bigint REFERENCES campaigns(id),
  relaunch_count  integer DEFAULT 0
);

CREATE INDEX idx_campaigns_status ON campaigns(status);
CREATE INDEX idx_campaigns_company ON campaigns(company_id);
CREATE INDEX idx_campaigns_brand ON campaigns(brand_id);
CREATE INDEX idx_campaigns_active_dates ON campaigns(status, start_date, end_date) WHERE status = 'active';
CREATE INDEX idx_campaigns_created_by ON campaigns(created_by);

-- 3c. campaign_reviews — references campaigns
CREATE TABLE campaign_reviews (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_id     bigint NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  reviewer_id     uuid NOT NULL REFERENCES auth.users(id),
  action          review_action NOT NULL,
  note            text,
  created_at      timestamptz DEFAULT now()
);

CREATE INDEX idx_reviews_campaign ON campaign_reviews(campaign_id, created_at DESC);

-- 3d. campaign_impressions — references campaigns + candidates
CREATE TABLE campaign_impressions (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_id     bigint NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  candidate_id    bigint NOT NULL REFERENCES candidates(id),
  impression_type text NOT NULL DEFAULT 'feed',
  created_at      timestamptz DEFAULT now(),
  UNIQUE(campaign_id, candidate_id, impression_type)
);

CREATE INDEX idx_impressions_campaign ON campaign_impressions(campaign_id);
CREATE INDEX idx_impressions_candidate ON campaign_impressions(candidate_id);

-- 3e. campaign_clicks
CREATE TABLE campaign_clicks (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_id     bigint NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  candidate_id    bigint NOT NULL REFERENCES candidates(id),
  click_type      text NOT NULL DEFAULT 'cta',
  created_at      timestamptz DEFAULT now()
);

CREATE INDEX idx_clicks_campaign ON campaign_clicks(campaign_id);

-- 3f. campaign_redemptions
CREATE TABLE campaign_redemptions (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_id     bigint NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  candidate_id    bigint NOT NULL REFERENCES candidates(id),
  redeemed_at     timestamptz DEFAULT now(),
  UNIQUE(campaign_id, candidate_id)
);

CREATE INDEX idx_redemptions_campaign ON campaign_redemptions(campaign_id);

-- 3g. inbox_messages — references campaigns, candidates, companies, brands
CREATE TABLE inbox_messages (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Recipient
  recipient_id    bigint NOT NULL REFERENCES candidates(id),

  -- Sender context
  sender_type     text NOT NULL,
  sender_user_id  uuid REFERENCES auth.users(id),
  company_id      bigint REFERENCES companies(id),
  brand_id        bigint REFERENCES brands(id),
  campaign_id     bigint REFERENCES campaigns(id),

  -- Content
  message_type    inbox_message_type NOT NULL DEFAULT 'campaign',
  title           text NOT NULL,
  body            text NOT NULL,
  cta_label       text,
  cta_url         text,
  cover_image_url text,

  -- State
  status          inbox_message_status NOT NULL DEFAULT 'pending',
  read_at         timestamptz,

  -- Timestamps
  created_at      timestamptz DEFAULT now(),
  delivered_at    timestamptz
);

CREATE INDEX idx_inbox_recipient ON inbox_messages(recipient_id, created_at DESC);
CREATE INDEX idx_inbox_campaign ON inbox_messages(campaign_id) WHERE campaign_id IS NOT NULL;
CREATE INDEX idx_inbox_unread ON inbox_messages(recipient_id, status) WHERE status != 'read';

-- 3h. email_jobs
CREATE TABLE email_jobs (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_id     bigint REFERENCES campaigns(id),
  recipient_id    bigint NOT NULL REFERENCES candidates(id),
  recipient_email text NOT NULL,

  -- Content snapshot
  subject         text NOT NULL,
  html_body       text NOT NULL,

  -- State
  status          email_job_status NOT NULL DEFAULT 'queued',
  sent_at         timestamptz,
  delivered_at    timestamptz,
  opened_at       timestamptz,
  clicked_at      timestamptz,
  error_message   text,

  created_at      timestamptz DEFAULT now()
);

CREATE INDEX idx_email_jobs_status ON email_jobs(status) WHERE status = 'queued';
CREATE INDEX idx_email_jobs_campaign ON email_jobs(campaign_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. ALTER TABLE candidates — new columns
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE candidates ADD COLUMN IF NOT EXISTS is_premium boolean DEFAULT false;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS premium_until timestamptz;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS unread_inbox_count integer DEFAULT 0;

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. TRIGGERS
-- ═══════════════════════════════════════════════════════════════════════════

-- 5a. campaigns.updated_at auto-update
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER campaigns_updated_at
  BEFORE UPDATE ON campaigns
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- 5b. inbox_messages → candidates.unread_inbox_count sync
CREATE OR REPLACE FUNCTION update_unread_inbox_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.status != 'read' THEN
    UPDATE candidates SET unread_inbox_count = COALESCE(unread_inbox_count, 0) + 1
    WHERE id = NEW.recipient_id;
  END IF;

  IF TG_OP = 'UPDATE' AND OLD.status != 'read' AND NEW.status = 'read' THEN
    UPDATE candidates SET unread_inbox_count = GREATEST(COALESCE(unread_inbox_count, 0) - 1, 0)
    WHERE id = NEW.recipient_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER inbox_unread_counter
  AFTER INSERT OR UPDATE OF status ON inbox_messages
  FOR EACH ROW EXECUTE FUNCTION update_unread_inbox_count();

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. HELPER FUNCTIONS (must be created BEFORE RLS policies that reference them)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (SELECT 1 FROM admin_users WHERE id = auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

CREATE OR REPLACE FUNCTION is_admin_role(required_role text)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (SELECT 1 FROM admin_users WHERE id = auth.uid() AND role = required_role);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. RLS POLICIES
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── campaigns ───
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;

CREATE POLICY campaigns_employer_select ON campaigns
  FOR SELECT USING (
    created_by = auth.uid() OR
    company_id IN (SELECT company_id FROM hr_profiles WHERE id = auth.uid() AND company_id IS NOT NULL)
  );

CREATE POLICY campaigns_employer_insert ON campaigns
  FOR INSERT WITH CHECK (
    created_by = auth.uid() AND
    company_id IN (SELECT company_id FROM hr_profiles WHERE id = auth.uid() AND company_id IS NOT NULL)
  );

CREATE POLICY campaigns_employer_update ON campaigns
  FOR UPDATE USING (
    created_by = auth.uid() AND
    status IN ('draft', 'revision_needed')
  );

CREATE POLICY campaigns_candidate_read ON campaigns
  FOR SELECT USING (
    status = 'active' AND
    EXISTS (
      SELECT 1 FROM candidates c
      WHERE c.user_id = auth.uid()
        AND (access_mode != 'premium_exclusive' OR c.is_premium = true)
    )
  );

CREATE POLICY campaigns_admin_all ON campaigns
  FOR ALL USING (is_admin());

-- ─── campaign_reviews ───
ALTER TABLE campaign_reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY reviews_admin_all ON campaign_reviews
  FOR ALL USING (is_admin());

CREATE POLICY reviews_employer_read ON campaign_reviews
  FOR SELECT USING (
    campaign_id IN (SELECT id FROM campaigns WHERE created_by = auth.uid())
  );

-- ─── campaign_impressions ───
ALTER TABLE campaign_impressions ENABLE ROW LEVEL SECURITY;

CREATE POLICY impressions_candidate_insert ON campaign_impressions
  FOR INSERT WITH CHECK (candidate_id = get_my_candidate_id());

CREATE POLICY impressions_employer_read ON campaign_impressions
  FOR SELECT USING (
    campaign_id IN (SELECT id FROM campaigns WHERE company_id IN (SELECT company_id FROM hr_profiles WHERE id = auth.uid()))
  );

CREATE POLICY impressions_admin ON campaign_impressions
  FOR SELECT USING (is_admin());

-- ─── campaign_clicks ───
ALTER TABLE campaign_clicks ENABLE ROW LEVEL SECURITY;

CREATE POLICY clicks_candidate_insert ON campaign_clicks
  FOR INSERT WITH CHECK (candidate_id = get_my_candidate_id());

CREATE POLICY clicks_employer_read ON campaign_clicks
  FOR SELECT USING (
    campaign_id IN (SELECT id FROM campaigns WHERE company_id IN (SELECT company_id FROM hr_profiles WHERE id = auth.uid()))
  );

CREATE POLICY clicks_admin ON campaign_clicks
  FOR SELECT USING (is_admin());

-- ─── campaign_redemptions ───
ALTER TABLE campaign_redemptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY redemptions_candidate_insert ON campaign_redemptions
  FOR INSERT WITH CHECK (candidate_id = get_my_candidate_id());

CREATE POLICY redemptions_employer_read ON campaign_redemptions
  FOR SELECT USING (
    campaign_id IN (SELECT id FROM campaigns WHERE company_id IN (SELECT company_id FROM hr_profiles WHERE id = auth.uid()))
  );

CREATE POLICY redemptions_admin ON campaign_redemptions
  FOR SELECT USING (is_admin());

-- ─── inbox_messages ───
ALTER TABLE inbox_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY inbox_candidate_select ON inbox_messages
  FOR SELECT USING (recipient_id = get_my_candidate_id());

CREATE POLICY inbox_candidate_update ON inbox_messages
  FOR UPDATE USING (recipient_id = get_my_candidate_id())
  WITH CHECK (recipient_id = get_my_candidate_id());

CREATE POLICY inbox_employer_select ON inbox_messages
  FOR SELECT USING (sender_user_id = auth.uid());

CREATE POLICY inbox_admin_all ON inbox_messages
  FOR ALL USING (is_admin());

-- ─── email_jobs ───
ALTER TABLE email_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY email_jobs_admin ON email_jobs
  FOR ALL USING (is_admin());

-- ─── admin_users ───
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_users_self_read ON admin_users
  FOR SELECT USING (id = auth.uid());

-- Uses SECURITY DEFINER helper to avoid infinite RLS recursion
CREATE POLICY admin_users_superadmin ON admin_users
  FOR ALL USING (is_admin_role('superadmin'));

-- ═══════════════════════════════════════════════════════════════════════════
-- 8. AUDIENCE TARGETING FUNCTION
-- ═══════════════════════════════════════════════════════════════════════════

-- Segment key mapping reference:
-- brands.segment stores: 'luxury', 'premium', 'mid', 'sportswear', 'beauty', 'tech'
-- campaigns.target_segments must use the SAME internal keys
-- UI mapping: luxury→LUXURY, premium→PREMIUM, mid→MODA, sportswear→SPORT, beauty→BEAUTY, tech→TECH

CREATE OR REPLACE FUNCTION get_campaign_audience(p_campaign_id bigint)
RETURNS TABLE(candidate_id bigint) AS $$
DECLARE
  v_campaign campaigns%ROWTYPE;
BEGIN
  SELECT * INTO v_campaign FROM campaigns WHERE id = p_campaign_id;

  RETURN QUERY
  SELECT c.id FROM candidates c
  WHERE c.is_active = true
    AND c.profile_completed = true
    -- City filter: uses candidate_location_preferences table
    AND (v_campaign.target_cities IS NULL OR
         EXISTS (
           SELECT 1 FROM candidate_location_preferences clp
           WHERE clp.candidate_id = c.id
           AND clp.city = ANY(v_campaign.target_cities)
         ))
    -- Segment filter via brand follows — uses INTERNAL keys
    AND (v_campaign.target_segments IS NULL OR
         EXISTS (
           SELECT 1 FROM candidate_brand_follows cbf
           JOIN brands b ON b.id = cbf.brand_id
           WHERE cbf.candidate_id = c.id
           AND b.segment = ANY(v_campaign.target_segments)
         ))
    -- Seniority filter: maps to deneyim_yil ranges
    AND (v_campaign.target_seniority IS NULL OR
         (
           ('junior' = ANY(v_campaign.target_seniority) AND COALESCE(c.deneyim_yil, 0) <= 2) OR
           ('mid' = ANY(v_campaign.target_seniority) AND c.deneyim_yil BETWEEN 3 AND 5) OR
           ('senior' = ANY(v_campaign.target_seniority) AND c.deneyim_yil BETWEEN 6 AND 10) OR
           ('manager' = ANY(v_campaign.target_seniority) AND c.deneyim_yil > 10)
         ))
    -- Distribution mode
    AND (
      CASE v_campaign.distribution_mode
        WHEN 'followers_only' THEN
          EXISTS (
            SELECT 1 FROM candidate_brand_follows cbf
            WHERE cbf.candidate_id = c.id AND cbf.brand_id = v_campaign.brand_id
          )
        WHEN 'followers_plus_similar' THEN
          EXISTS (
            SELECT 1 FROM candidate_brand_follows cbf
            WHERE cbf.candidate_id = c.id AND cbf.brand_id = v_campaign.brand_id
          )
          OR EXISTS (
            SELECT 1 FROM candidate_brand_follows cbf2
            JOIN brands b2 ON b2.id = cbf2.brand_id
            WHERE cbf2.candidate_id = c.id
            AND b2.segment = ANY(
              SELECT b3.segment FROM brands b3 WHERE b3.id = v_campaign.brand_id
            )
          )
        WHEN 'broad_discovery' THEN true
        ELSE false
      END
    )
    -- Access mode: premium filter
    AND (
      CASE v_campaign.access_mode
        WHEN 'premium_exclusive' THEN c.is_premium = true
        ELSE true
      END
    )
    -- Blocked company filter
    AND NOT EXISTS (
      SELECT 1 FROM candidate_blocked_companies cbc
      WHERE cbc.candidate_id = c.id AND cbc.company_id = v_campaign.company_id
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- ═══════════════════════════════════════════════════════════════════════════
-- 9. CAMPAIGN LIFECYCLE CRON FUNCTIONS
-- ═══════════════════════════════════════════════════════════════════════════

-- approved → active (payment captured at approve time, visibility delayed by start_date)
CREATE OR REPLACE FUNCTION activate_due_campaigns()
RETURNS void AS $$
BEGIN
  UPDATE campaigns
  SET status = 'active', published_at = now()
  WHERE status = 'approved'
    AND payment_status = 'captured'
    AND (start_date IS NULL OR start_date <= now());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- active → ended (end_date passed)
CREATE OR REPLACE FUNCTION end_expired_campaigns()
RETURNS void AS $$
BEGIN
  UPDATE campaigns
  SET status = 'ended', ended_at = now()
  WHERE status = 'active'
    AND end_date <= now();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ended → archived (7 days after ending)
CREATE OR REPLACE FUNCTION archive_old_ended_campaigns()
RETURNS void AS $$
BEGIN
  UPDATE campaigns
  SET status = 'archived', archived_at = now()
  WHERE status = 'ended'
    AND ended_at < now() - interval '7 days';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- pg_cron schedules (run manually via Supabase dashboard > Database > Extensions > pg_cron):
-- SELECT cron.schedule('activate-campaigns', '*/5 * * * *', 'SELECT activate_due_campaigns()');
-- SELECT cron.schedule('end-campaigns', '*/5 * * * *', 'SELECT end_expired_campaigns()');
-- SELECT cron.schedule('archive-campaigns', '0 3 * * *', 'SELECT archive_old_ended_campaigns()');

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════
-- 10. POST-MIGRATION: Admin user seed (run separately after COMMIT)
-- Replace YOUR_AUTH_USER_ID with your actual auth.users UUID
-- ═══════════════════════════════════════════════════════════════════════════
-- INSERT INTO admin_users (id, role, display_name)
-- VALUES ('YOUR_AUTH_USER_ID', 'superadmin', 'Admin');

-- ═══════════════════════════════════════════════════════════════════════════
-- PRE-FLIGHT VERIFICATION (run BEFORE migration to check prerequisites)
-- ═══════════════════════════════════════════════════════════════════════════
-- These columns MUST exist on candidates for get_campaign_audience() to work.
-- If any returns 0 rows, you need to add the column or adjust the function.
--
-- SELECT column_name FROM information_schema.columns
-- WHERE table_name = 'candidates' AND column_name IN ('deneyim_yil', 'profile_completed', 'is_active');
--
-- This function MUST exist for cbf_employer_read policy:
-- SELECT proname FROM pg_proc WHERE proname = 'is_employer';
--
-- ═══════════════════════════════════════════════════════════════════════════
-- POST-MIGRATION VERIFICATION (run AFTER migration)
-- ═══════════════════════════════════════════════════════════════════════════
-- 1. Tables created:
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public'
-- AND (table_name LIKE 'campaign%' OR table_name IN ('inbox_messages', 'email_jobs', 'admin_users', 'candidate_brand_follows'))
-- ORDER BY table_name;
--
-- 2. Enums created:
-- SELECT typname FROM pg_type
-- WHERE typname IN ('campaign_type', 'campaign_status', 'distribution_mode', 'access_mode',
--                   'campaign_package', 'payment_status', 'review_action',
--                   'inbox_message_type', 'inbox_message_status', 'email_job_status');
--
-- 3. Candidates new columns:
-- SELECT column_name, data_type, column_default FROM information_schema.columns
-- WHERE table_name = 'candidates' AND column_name IN ('is_premium', 'premium_until', 'unread_inbox_count');
--
-- 4. Brands segment column:
-- SELECT column_name FROM information_schema.columns
-- WHERE table_name = 'brands' AND column_name = 'segment';
--
-- 5. RLS policies count (should be ~15+):
-- SELECT tablename, COUNT(*) FROM pg_policies
-- WHERE tablename IN ('campaigns', 'campaign_reviews', 'campaign_impressions',
--                     'campaign_clicks', 'campaign_redemptions', 'inbox_messages',
--                     'email_jobs', 'admin_users', 'candidate_brand_follows')
-- GROUP BY tablename ORDER BY tablename;
