-- Migration 020: Positions table (localStorage → Supabase)
-- Employers can create/manage job positions backed by real database

CREATE TABLE IF NOT EXISTS positions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hr_profile_id uuid NOT NULL REFERENCES hr_profiles(id) ON DELETE CASCADE,
  company_id bigint REFERENCES companies(id) ON DELETE SET NULL,
  ad text NOT NULL,
  sehir text,
  exp text,
  seg text,
  maas text,
  aciklama text,
  durum text NOT NULL DEFAULT 'active' CHECK (durum IN ('active', 'draft', 'closed')),
  gorunum int NOT NULL DEFAULT 0,
  basvuru int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Index for employer queries
CREATE INDEX idx_positions_hr_profile ON positions(hr_profile_id);
CREATE INDEX idx_positions_company ON positions(company_id);

-- RLS
ALTER TABLE positions ENABLE ROW LEVEL SECURITY;

-- Employers can read their own positions
CREATE POLICY positions_select_own ON positions
  FOR SELECT USING (hr_profile_id = auth.uid());

-- Employers can insert their own positions
CREATE POLICY positions_insert_own ON positions
  FOR INSERT WITH CHECK (hr_profile_id = auth.uid());

-- Employers can update their own positions
CREATE POLICY positions_update_own ON positions
  FOR UPDATE USING (hr_profile_id = auth.uid());

-- Employers can delete their own positions
CREATE POLICY positions_delete_own ON positions
  FOR DELETE USING (hr_profile_id = auth.uid());

-- Admin read (for admin panel)
CREATE POLICY positions_admin_read ON positions
  FOR SELECT USING (
    auth.uid() IN (SELECT id FROM hr_profiles WHERE employer_role = 'admin')
  );

-- Updated_at trigger
CREATE OR REPLACE TRIGGER positions_updated_at
  BEFORE UPDATE ON positions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();
