-- Migration 025: Employer favorites (localStorage → Supabase)
-- Persists employer favorites across devices/browsers.
-- Replaces ht_ik_favs localStorage with database-backed storage.

CREATE TABLE IF NOT EXISTS employer_favorites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hr_profile_id uuid NOT NULL REFERENCES hr_profiles(id) ON DELETE CASCADE,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Prevent duplicate favorites
CREATE UNIQUE INDEX IF NOT EXISTS idx_employer_favorites_unique
  ON employer_favorites(hr_profile_id, candidate_id);

-- Fast lookup by employer
CREATE INDEX IF NOT EXISTS idx_employer_favorites_hr
  ON employer_favorites(hr_profile_id);

-- RLS
ALTER TABLE employer_favorites ENABLE ROW LEVEL SECURITY;

-- Employers can read their own favorites
CREATE POLICY employer_favorites_select_own ON employer_favorites
  FOR SELECT USING (hr_profile_id = auth.uid());

-- Employers can insert their own favorites
CREATE POLICY employer_favorites_insert_own ON employer_favorites
  FOR INSERT WITH CHECK (hr_profile_id = auth.uid());

-- Employers can delete their own favorites
CREATE POLICY employer_favorites_delete_own ON employer_favorites
  FOR DELETE USING (hr_profile_id = auth.uid());

-- Admin read access
CREATE POLICY employer_favorites_admin_read ON employer_favorites
  FOR SELECT USING (is_admin());
