-- Migration 026: Candidate → Company follows
-- Allows candidates to follow companies (not just brands).
-- Foundation for P3 communication system: follow → match → DM.
-- Coexists with candidate_brand_follows (migration 014) until brand→company migration.

CREATE TABLE IF NOT EXISTS candidate_company_follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Prevent duplicate follows
CREATE UNIQUE INDEX IF NOT EXISTS idx_ccf_unique
  ON candidate_company_follows(candidate_id, company_id);

-- Fast lookup by company (employer dashboard)
CREATE INDEX IF NOT EXISTS idx_ccf_company
  ON candidate_company_follows(company_id);

-- RLS
ALTER TABLE candidate_company_follows ENABLE ROW LEVEL SECURITY;

-- Candidates manage their own follows
CREATE POLICY ccf_select_own ON candidate_company_follows
  FOR SELECT USING (candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid()));

CREATE POLICY ccf_insert_own ON candidate_company_follows
  FOR INSERT WITH CHECK (candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid()));

CREATE POLICY ccf_delete_own ON candidate_company_follows
  FOR DELETE USING (candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid()));

-- Employers see followers of their company
CREATE POLICY ccf_employer_read ON candidate_company_follows
  FOR SELECT USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
  );

-- Admin read
CREATE POLICY ccf_admin_read ON candidate_company_follows
  FOR SELECT USING (is_admin());
