-- Migration 027: Company locations
-- Employers can list store/office locations by city.
-- Powers location-based candidate matching and company profiles.

CREATE TABLE IF NOT EXISTS company_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  sehir text NOT NULL,
  konum_tipi text NOT NULL DEFAULT 'store'
    CHECK (konum_tipi IN ('store', 'office', 'headquarters', 'warehouse')),
  adres text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Index for company queries
CREATE INDEX IF NOT EXISTS idx_company_locations_company
  ON company_locations(company_id);

-- RLS
ALTER TABLE company_locations ENABLE ROW LEVEL SECURITY;

-- Public read (candidates can see company locations)
CREATE POLICY cl_public_read ON company_locations
  FOR SELECT USING (true);

-- Employers manage their own company locations
CREATE POLICY cl_employer_insert ON company_locations
  FOR INSERT WITH CHECK (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
  );

CREATE POLICY cl_employer_update ON company_locations
  FOR UPDATE USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
  );

CREATE POLICY cl_employer_delete ON company_locations
  FOR DELETE USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
  );

-- Admin full access
CREATE POLICY cl_admin_all ON company_locations
  FOR ALL USING (is_admin());
