-- ═══════════════════════════════════════════════════════════════
-- Migration 029: Company Teams + Invitations
-- Date: 2026-03-16
-- Type: SCHEMA — team system for multi-brand employers
--
-- Purpose:
--   1. company_teams: organize HR staff by brand/department
--   2. company_invitations: admin invites new team members
--   3. hr_profiles.team_id FK (nullable — solo employers have no team)
--
-- Flow:
--   Admin creates team → sends invitation (email) → invitee signs up →
--   register_employer() or accept flow links them to company + team
--
-- Depends on: 008 (hr_profiles), 012 (companies, brands), 028 (employer_role)
-- ═══════════════════════════════════════════════════════════════


-- ── 1. COMPANY TEAMS ───────────────────────────────────────────
-- Teams are optional groupings within a company.
-- For tek_marka employers, they may have one default team or none.
-- For coklu_marka, teams typically map to brands.

CREATE TABLE IF NOT EXISTS company_teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  brand_id bigint REFERENCES brands(id) ON DELETE SET NULL,
  team_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Index for company queries
CREATE INDEX IF NOT EXISTS idx_company_teams_company
  ON company_teams(company_id);

-- Unique team name per company
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'company_teams'::regclass
      AND conname = 'company_teams_name_unique'
  ) THEN
    ALTER TABLE company_teams
      ADD CONSTRAINT company_teams_name_unique
      UNIQUE (company_id, team_name);
  END IF;
END
$$;


-- ── 2. COMPANY INVITATIONS ─────────────────────────────────────
-- Admin invites a colleague by email + role + optional team.
-- Status flow: pending → accepted | expired | cancelled

CREATE TABLE IF NOT EXISTS company_invitations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  invited_email text NOT NULL,
  invited_role text NOT NULL DEFAULT 'recruiter'
    CHECK (invited_role IN ('admin', 'recruiter', 'viewer')),
  team_id bigint REFERENCES company_teams(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'expired', 'cancelled')),
  invited_by uuid NOT NULL REFERENCES hr_profiles(id) ON DELETE CASCADE,
  accepted_by uuid REFERENCES hr_profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days')
);

-- Index for lookup by email (invitee checking their invitations)
CREATE INDEX IF NOT EXISTS idx_invitations_email
  ON company_invitations(invited_email);

-- Index for company dashboard (list invitations)
CREATE INDEX IF NOT EXISTS idx_invitations_company
  ON company_invitations(company_id);

-- Prevent duplicate pending invitations for same email+company
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE tablename = 'company_invitations'
      AND indexname = 'idx_invitations_pending_unique'
  ) THEN
    CREATE UNIQUE INDEX idx_invitations_pending_unique
      ON company_invitations(company_id, invited_email)
      WHERE status = 'pending';
  END IF;
END
$$;


-- ── 3. HR_PROFILES.TEAM_ID ────────────────────────────────────
-- Nullable FK: solo employers and admins may not belong to a team.

ALTER TABLE hr_profiles ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES company_teams(id) ON DELETE SET NULL;


-- ── 4. RLS — COMPANY TEAMS ─────────────────────────────────────

ALTER TABLE company_teams ENABLE ROW LEVEL SECURITY;

-- Employers can read teams in their company
CREATE POLICY ct_employer_read ON company_teams
  FOR SELECT USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
  );

-- Only admin can create teams
CREATE POLICY ct_admin_insert ON company_teams
  FOR INSERT WITH CHECK (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
    AND (SELECT employer_role FROM hr_profiles WHERE id = auth.uid()) = 'admin'
  );

-- Only admin can update teams
CREATE POLICY ct_admin_update ON company_teams
  FOR UPDATE USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
    AND (SELECT employer_role FROM hr_profiles WHERE id = auth.uid()) = 'admin'
  );

-- Only admin can delete teams
CREATE POLICY ct_admin_delete ON company_teams
  FOR DELETE USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
    AND (SELECT employer_role FROM hr_profiles WHERE id = auth.uid()) = 'admin'
  );

-- Admin full access
CREATE POLICY ct_superadmin ON company_teams
  FOR ALL USING (is_admin());


-- ── 5. RLS — COMPANY INVITATIONS ───────────────────────────────

ALTER TABLE company_invitations ENABLE ROW LEVEL SECURITY;

-- Employers can read invitations for their company
CREATE POLICY ci_employer_read ON company_invitations
  FOR SELECT USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
  );

-- Only admin can create invitations
CREATE POLICY ci_admin_insert ON company_invitations
  FOR INSERT WITH CHECK (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
    AND (SELECT employer_role FROM hr_profiles WHERE id = auth.uid()) = 'admin'
    AND invited_by = auth.uid()
  );

-- Only admin can cancel invitations (update status)
CREATE POLICY ci_admin_update ON company_invitations
  FOR UPDATE USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
    AND (SELECT employer_role FROM hr_profiles WHERE id = auth.uid()) = 'admin'
  );

-- Invitee can read their own invitation by email
CREATE POLICY ci_invitee_read ON company_invitations
  FOR SELECT USING (
    invited_email = (SELECT email FROM auth.users WHERE id = auth.uid())
  );

-- Admin full access
CREATE POLICY ci_superadmin ON company_invitations
  FOR ALL USING (is_admin());


-- ═══════════════════════════════════════════════════════════════
-- VERIFICATION
-- ═══════════════════════════════════════════════════════════════
-- SELECT * FROM company_teams LIMIT 0;
-- SELECT * FROM company_invitations LIMIT 0;
-- SELECT column_name FROM information_schema.columns
--   WHERE table_name = 'hr_profiles' AND column_name = 'team_id';
