-- ═══════════════════════════════════════════════════════════════
-- Migration 031: Employer Messages + Templates
-- Date: 2026-03-16
-- Type: SCHEMA — employer→candidate messaging system
--
-- Purpose:
--   1. employer_messages: DM from employer to candidate
--   2. message_templates: reusable templates per company + system defaults
--   3. RLS: employer manages own, candidate reads own
--
-- Flow:
--   Employer opens candidate drawer → clicks "Mesaj Gönder" →
--   picks template + position → sends → candidate sees in inbox
--
-- Depends on: 008 (hr_profiles), 001 (candidates), 012 (companies),
--             020 (positions), 028 (employer_role)
-- ═══════════════════════════════════════════════════════════════


-- ── 1. MESSAGE TEMPLATES ─────────────────────────────────────
-- Company-specific + system defaults (is_system = true).
-- System templates have company_id = NULL.

CREATE TABLE IF NOT EXISTS message_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint REFERENCES companies(id) ON DELETE CASCADE,
  template_name text NOT NULL,
  subject_template text NOT NULL,
  body_template text NOT NULL,
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_msg_templates_company
  ON message_templates(company_id);


-- ── 2. EMPLOYER MESSAGES ─────────────────────────────────────
-- One-way: employer → candidate. Not a chat — a structured offer/message.
-- position_id nullable: not every message is about a specific position.

CREATE TABLE IF NOT EXISTS employer_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid NOT NULL REFERENCES hr_profiles(id) ON DELETE CASCADE,
  company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  position_id bigint REFERENCES positions(id) ON DELETE SET NULL,
  template_id bigint REFERENCES message_templates(id) ON DELETE SET NULL,
  subject text NOT NULL,
  body text NOT NULL,
  status text NOT NULL DEFAULT 'sent'
    CHECK (status IN ('sent', 'read', 'archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz
);

-- Index for candidate inbox (most common query)
CREATE INDEX IF NOT EXISTS idx_emp_messages_candidate
  ON employer_messages(candidate_id, created_at DESC);

-- Index for employer sent messages
CREATE INDEX IF NOT EXISTS idx_emp_messages_sender
  ON employer_messages(sender_id, created_at DESC);

-- Index for company message history
CREATE INDEX IF NOT EXISTS idx_emp_messages_company
  ON employer_messages(company_id);


-- ── 3. RLS — MESSAGE TEMPLATES ───────────────────────────────

ALTER TABLE message_templates ENABLE ROW LEVEL SECURITY;

-- Everyone can read system templates
CREATE POLICY mt_system_read ON message_templates
  FOR SELECT USING (is_system = true);

-- Employers can read their company's templates
CREATE POLICY mt_employer_read ON message_templates
  FOR SELECT USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
  );

-- Only admin can manage company templates
CREATE POLICY mt_admin_insert ON message_templates
  FOR INSERT WITH CHECK (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
    AND (SELECT employer_role FROM hr_profiles WHERE id = auth.uid()) = 'admin'
  );

CREATE POLICY mt_admin_update ON message_templates
  FOR UPDATE USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
    AND (SELECT employer_role FROM hr_profiles WHERE id = auth.uid()) = 'admin'
  );

CREATE POLICY mt_admin_delete ON message_templates
  FOR DELETE USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
    AND (SELECT employer_role FROM hr_profiles WHERE id = auth.uid()) = 'admin'
  );

-- Superadmin full access
CREATE POLICY mt_superadmin ON message_templates
  FOR ALL USING (is_admin());


-- ── 4. RLS — EMPLOYER MESSAGES ───────────────────────────────

ALTER TABLE employer_messages ENABLE ROW LEVEL SECURITY;

-- Employer can read messages from their company
CREATE POLICY em_employer_read ON employer_messages
  FOR SELECT USING (
    is_employer()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
  );

-- Employer can send messages (insert)
CREATE POLICY em_employer_insert ON employer_messages
  FOR INSERT WITH CHECK (
    is_employer()
    AND sender_id = auth.uid()
    AND company_id = (SELECT company_id FROM hr_profiles WHERE id = auth.uid())
  );

-- Candidate can read messages sent to them
CREATE POLICY em_candidate_read ON employer_messages
  FOR SELECT USING (
    candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid())
  );

-- Candidate can update status (mark as read/archived)
CREATE POLICY em_candidate_update ON employer_messages
  FOR UPDATE USING (
    candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid())
  )
  WITH CHECK (
    candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid())
  );

-- Superadmin full access
CREATE POLICY em_superadmin ON employer_messages
  FOR ALL USING (is_admin());


-- ── 5. HELPER: get_my_candidate_id (if not exists) ──────────
-- Used by candidate RLS. May already exist from earlier migrations.

CREATE OR REPLACE FUNCTION get_my_candidate_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id FROM candidates WHERE user_id = auth.uid();
$$;


-- ── 6. SEND MESSAGE FUNCTION ─────────────────────────────────
-- SECURITY DEFINER: validates sender, enforces company match,
-- checks candidate exists and is active.

CREATE OR REPLACE FUNCTION send_employer_message(
  p_candidate_id bigint,
  p_subject text,
  p_body text,
  p_position_id bigint DEFAULT NULL,
  p_template_id bigint DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_company_id bigint;
  v_msg_id bigint;
  v_candidate_active boolean;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- Get employer's company
  SELECT company_id INTO v_company_id
  FROM hr_profiles WHERE id = v_user_id;

  IF v_company_id IS NULL THEN
    RAISE EXCEPTION 'Employer not linked to a company';
  END IF;

  -- Verify candidate exists and is active
  SELECT is_active INTO v_candidate_active
  FROM candidates WHERE id = p_candidate_id;

  IF v_candidate_active IS NULL THEN
    RAISE EXCEPTION 'Candidate not found';
  END IF;

  IF NOT v_candidate_active THEN
    RAISE EXCEPTION 'Candidate profile is not active';
  END IF;

  -- Verify position belongs to this company (if provided)
  IF p_position_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM positions
      WHERE id = p_position_id AND company_id = v_company_id
    ) THEN
      RAISE EXCEPTION 'Position does not belong to your company';
    END IF;
  END IF;

  -- Insert message
  INSERT INTO employer_messages (sender_id, company_id, candidate_id, position_id, template_id, subject, body)
  VALUES (v_user_id, v_company_id, p_candidate_id, p_position_id, p_template_id, TRIM(p_subject), TRIM(p_body))
  RETURNING id INTO v_msg_id;

  RETURN v_msg_id;
END;
$$;

GRANT EXECUTE ON FUNCTION send_employer_message TO authenticated;


-- ── 7. MARK MESSAGE READ ─────────────────────────────────────
-- Candidate marks a message as read.

CREATE OR REPLACE FUNCTION mark_message_read(p_message_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
BEGIN
  v_candidate_id := get_my_candidate_id();
  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Not a candidate';
  END IF;

  UPDATE employer_messages
  SET status = 'read', read_at = now()
  WHERE id = p_message_id
    AND candidate_id = v_candidate_id
    AND status = 'sent';
END;
$$;

GRANT EXECUTE ON FUNCTION mark_message_read TO authenticated;


-- ── 8. SEED SYSTEM TEMPLATES ─────────────────────────────────
-- Default templates available to all employers.
-- company_id = NULL + is_system = true

INSERT INTO message_templates (company_id, template_name, subject_template, body_template, is_system)
VALUES
  (NULL, 'Pozisyon Teklifi',
   '{{pozisyon}} pozisyonu için davet',
   'Merhaba,

{{sirket}} olarak profilinizi inceledik ve {{pozisyon}} pozisyonumuz için uygun olabileceğinizi düşünüyoruz.

Sizinle görüşmek isteriz. Uygun olduğunuz bir zamanda bize dönüş yapmanızı rica ederiz.

Saygılarımızla,
{{sirket}} İK Ekibi',
   true),

  (NULL, 'Genel Tanışma',
   '{{sirket}} size ulaşmak istiyor',
   'Merhaba,

{{sirket}} İK ekibi olarak profilinizi beğendik. Şu an açık pozisyonlarımız arasında size uygun fırsatlar olabileceğini düşünüyoruz.

Kısa bir tanışma görüşmesi yapmak ister misiniz?

Saygılarımızla,
{{sirket}} İK Ekibi',
   true),

  (NULL, 'Mülakat Daveti',
   '{{pozisyon}} için mülakat daveti',
   'Merhaba,

{{sirket}} olarak {{pozisyon}} pozisyonu başvurunuzu olumlu değerlendirdik.

Sizinle bir mülakat gerçekleştirmek istiyoruz. Uygun olduğunuz tarih ve saatleri bize iletmenizi rica ederiz.

Saygılarımızla,
{{sirket}} İK Ekibi',
   true)
ON CONFLICT DO NOTHING;


-- ═══════════════════════════════════════════════════════════════
-- VERIFICATION
-- ═══════════════════════════════════════════════════════════════
-- SELECT * FROM message_templates WHERE is_system = true;
-- SELECT * FROM employer_messages LIMIT 0;
