-- ═══════════════════════════════════════════════════════════════
-- Migration 033: Subscriptions & Premium System
-- Date: 2026-03-16
-- Type: SCHEMA — subscription tracking for employer + candidate premium
--
-- Purpose:
--   1. subscriptions table: tracks premium plans for both user types
--   2. Helper functions: is_premium_employer(), get_employer_plan()
--   3. Usage tracking: employer_daily_usage for rate-limiting free tier
--
-- Tiers (from isveren.html):
--   Demo (free): 5 candidate views, 1 position, no DM
--   Pro: unlimited views, DM, position filtering, priority support
--   Enterprise: Pro + multi-branch, analytics, API, dedicated advisor
--
-- Depends on: 008 (hr_profiles), 001 (candidates), 019 (is_employer)
-- ═══════════════════════════════════════════════════════════════


-- ── 1. SUBSCRIPTIONS TABLE ─────────────────────────────────────
-- One row per subscription period. Renewal = new row.
-- Churn = status expired/cancelled. Re-acquisition = new active row.

CREATE TABLE IF NOT EXISTS subscriptions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_type text NOT NULL CHECK (user_type IN ('candidate', 'employer')),
  plan text NOT NULL CHECK (plan IN ('pro', 'enterprise')),
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'trial', 'expired', 'cancelled')),
  auto_renew boolean NOT NULL DEFAULT true,
  amount integer NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'TRY',
  started_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  renewed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_subscriptions_user
  ON subscriptions(user_id, user_type);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status
  ON subscriptions(status, expires_at);
CREATE INDEX IF NOT EXISTS idx_subscriptions_type_status
  ON subscriptions(user_type, status);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION update_subscriptions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER subscriptions_updated_at
  BEFORE UPDATE ON subscriptions
  FOR EACH ROW EXECUTE FUNCTION update_subscriptions_updated_at();


-- ── 2. RLS ─────────────────────────────────────────────────────

ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- Users can read their own subscriptions
CREATE POLICY subscriptions_user_read ON subscriptions
  FOR SELECT USING (user_id = auth.uid());

-- Admin full access
CREATE POLICY subscriptions_admin_all ON subscriptions
  FOR ALL USING (is_admin());


-- ── 3. EMPLOYER DAILY USAGE TRACKING ───────────────────────────
-- Tracks candidate profile views per day for free tier rate-limiting.
-- Pro/Enterprise skip this check.

CREATE TABLE IF NOT EXISTS employer_daily_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  usage_date date NOT NULL DEFAULT CURRENT_DATE,
  candidate_views integer NOT NULL DEFAULT 0,
  messages_sent integer NOT NULL DEFAULT 0,
  UNIQUE(user_id, usage_date)
);

CREATE INDEX IF NOT EXISTS idx_employer_daily_usage_user_date
  ON employer_daily_usage(user_id, usage_date);

ALTER TABLE employer_daily_usage ENABLE ROW LEVEL SECURITY;

CREATE POLICY edu_user_read ON employer_daily_usage
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY edu_admin_all ON employer_daily_usage
  FOR ALL USING (is_admin());


-- ── 4. HELPER: is_premium_employer() ───────────────────────────
-- Returns true if the current user has an active pro/enterprise subscription.

CREATE OR REPLACE FUNCTION is_premium_employer()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM subscriptions
    WHERE user_id = auth.uid()
      AND user_type = 'employer'
      AND plan IN ('pro', 'enterprise')
      AND status IN ('active', 'trial')
      AND expires_at > now()
  );
END;
$$;


-- ── 5. HELPER: get_employer_plan() ─────────────────────────────
-- Returns the current plan name for the employer, or 'demo' if none.

CREATE OR REPLACE FUNCTION get_employer_plan()
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_plan text;
BEGIN
  SELECT plan INTO v_plan
  FROM subscriptions
  WHERE user_id = auth.uid()
    AND user_type = 'employer'
    AND status IN ('active', 'trial')
    AND expires_at > now()
  ORDER BY
    CASE plan WHEN 'enterprise' THEN 1 WHEN 'pro' THEN 2 ELSE 3 END
  LIMIT 1;

  RETURN COALESCE(v_plan, 'demo');
END;
$$;


-- ── 6. HELPER: check_employer_usage_limit() ────────────────────
-- Returns true if the employer can still perform the action today.
-- Pro/Enterprise always return true. Demo has limits.
-- action: 'candidate_view' (limit 5/day) or 'message' (limit 0 for demo)

CREATE OR REPLACE FUNCTION check_employer_usage_limit(p_action text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_plan text;
  v_usage record;
BEGIN
  -- Only employers have usage limits
  IF NOT is_employer() THEN RETURN true; END IF;

  v_plan := get_employer_plan();

  -- Pro and Enterprise have no limits
  IF v_plan IN ('pro', 'enterprise') THEN
    RETURN true;
  END IF;

  -- Demo limits
  SELECT candidate_views, messages_sent INTO v_usage
  FROM employer_daily_usage
  WHERE user_id = auth.uid() AND usage_date = CURRENT_DATE;

  IF p_action = 'candidate_view' THEN
    RETURN COALESCE(v_usage.candidate_views, 0) < 5;
  ELSIF p_action = 'message' THEN
    -- Demo users cannot send messages
    RETURN false;
  END IF;

  RETURN true;
END;
$$;


-- ── 7. HELPER: increment_employer_usage() ──────────────────────
-- Increments the daily usage counter. Called after a successful action.

CREATE OR REPLACE FUNCTION increment_employer_usage(p_action text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_employer() THEN RETURN; END IF;

  INSERT INTO employer_daily_usage (user_id, usage_date, candidate_views, messages_sent)
  VALUES (
    auth.uid(),
    CURRENT_DATE,
    CASE WHEN p_action = 'candidate_view' THEN 1 ELSE 0 END,
    CASE WHEN p_action = 'message' THEN 1 ELSE 0 END
  )
  ON CONFLICT (user_id, usage_date)
  DO UPDATE SET
    candidate_views = employer_daily_usage.candidate_views +
      CASE WHEN p_action = 'candidate_view' THEN 1 ELSE 0 END,
    messages_sent = employer_daily_usage.messages_sent +
      CASE WHEN p_action = 'message' THEN 1 ELSE 0 END;
END;
$$;

GRANT EXECUTE ON FUNCTION is_premium_employer TO authenticated;
GRANT EXECUTE ON FUNCTION get_employer_plan TO authenticated;
GRANT EXECUTE ON FUNCTION check_employer_usage_limit TO authenticated;
GRANT EXECUTE ON FUNCTION increment_employer_usage TO authenticated;


-- ═══════════════════════════════════════════════════════════════
-- VERIFICATION
-- ═══════════════════════════════════════════════════════════════
-- SELECT get_employer_plan(); -- should return 'demo' for free users
-- SELECT check_employer_usage_limit('candidate_view'); -- should return true (0 < 5)
-- SELECT check_employer_usage_limit('message'); -- should return false for demo
