-- ═══════════════════════════════════════════════════════════════
-- Migration 034: SMS Phone Verification System
-- Date: 2026-03-16
-- Type: SCHEMA — OTP-based phone verification for candidates
--
-- Purpose:
--   1. phone_verifications table: stores OTP codes with expiry
--   2. candidates.phone_verified flag: tracks verified status
--   3. Helper functions for OTP create/verify flow
--
-- Flow:
--   Candidate enters phone → requests OTP → receives SMS →
--   enters code → verify_phone_otp() validates → phone_verified = true
--
-- SMS provider: Twilio or Supabase Phone Auth (configured externally)
-- This migration handles the DB layer only.
--
-- Depends on: 001 (candidates)
-- ═══════════════════════════════════════════════════════════════


-- ── 1. ADD phone_verified TO CANDIDATES ────────────────────────

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS phone_verified boolean NOT NULL DEFAULT false;

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS phone_verified_at timestamptz;


-- ── 2. PHONE VERIFICATIONS TABLE ───────────────────────────────
-- Stores OTP codes. Short-lived (5 min expiry). Max 5 attempts per day.

CREATE TABLE IF NOT EXISTS phone_verifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  telefon text NOT NULL,
  otp_code text NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 3,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'verified', 'expired', 'failed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '5 minutes'),
  verified_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_phone_verifications_user
  ON phone_verifications(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_phone_verifications_status
  ON phone_verifications(status, expires_at);

-- RLS
ALTER TABLE phone_verifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY pv_user_read ON phone_verifications
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY pv_admin_all ON phone_verifications
  FOR ALL USING (is_admin());


-- ── 3. REQUEST OTP ─────────────────────────────────────────────
-- Creates an OTP record. Returns the OTP code (for the backend
-- SMS sender to use). Rate-limited to 5 requests per day.
-- IMPORTANT: In production, the OTP should be sent via Edge Function,
-- NOT returned to the client. This function is the DB layer only.

CREATE OR REPLACE FUNCTION request_phone_otp(p_telefon text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_candidate_id bigint;
  v_daily_count integer;
  v_otp text;
  v_record_id bigint;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Giriş yapmalısınız');
  END IF;

  -- Verify caller is a candidate
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = v_user_id;
  IF v_candidate_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Aday profili bulunamadı');
  END IF;

  -- Rate limit: max 5 OTP requests per day
  SELECT COUNT(*) INTO v_daily_count
  FROM phone_verifications
  WHERE user_id = v_user_id
    AND created_at > (now() - interval '24 hours');

  IF v_daily_count >= 5 THEN
    RETURN json_build_object('success', false, 'error', 'Günlük doğrulama limiti aşıldı. 24 saat sonra tekrar deneyin.');
  END IF;

  -- Expire any pending OTPs for this user
  UPDATE phone_verifications
  SET status = 'expired'
  WHERE user_id = v_user_id AND status = 'pending';

  -- Generate 6-digit OTP
  v_otp := LPAD(FLOOR(RANDOM() * 1000000)::text, 6, '0');

  -- Insert new OTP record
  INSERT INTO phone_verifications (user_id, telefon, otp_code)
  VALUES (v_user_id, TRIM(p_telefon), v_otp)
  RETURNING id INTO v_record_id;

  RETURN json_build_object(
    'success', true,
    'verification_id', v_record_id,
    'expires_in_seconds', 300
  );
END;
$$;


-- ── 4. VERIFY OTP ──────────────────────────────────────────────
-- Validates the OTP code. On success, sets phone_verified = true.

CREATE OR REPLACE FUNCTION verify_phone_otp(p_verification_id bigint, p_code text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_record record;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Giriş yapmalısınız');
  END IF;

  -- Fetch the verification record
  SELECT * INTO v_record
  FROM phone_verifications
  WHERE id = p_verification_id
    AND user_id = v_user_id;

  IF v_record IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Doğrulama kaydı bulunamadı');
  END IF;

  IF v_record.status != 'pending' THEN
    RETURN json_build_object('success', false, 'error', 'Bu doğrulama kodu artık geçerli değil');
  END IF;

  IF v_record.expires_at < now() THEN
    UPDATE phone_verifications SET status = 'expired' WHERE id = p_verification_id;
    RETURN json_build_object('success', false, 'error', 'Doğrulama kodunun süresi doldu');
  END IF;

  -- Increment attempts
  UPDATE phone_verifications
  SET attempts = attempts + 1
  WHERE id = p_verification_id;

  IF v_record.attempts >= v_record.max_attempts THEN
    UPDATE phone_verifications SET status = 'failed' WHERE id = p_verification_id;
    RETURN json_build_object('success', false, 'error', 'Maksimum deneme sayısına ulaşıldı');
  END IF;

  -- Check code
  IF TRIM(p_code) != v_record.otp_code THEN
    RETURN json_build_object('success', false, 'error', 'Doğrulama kodu hatalı', 'remaining_attempts', v_record.max_attempts - v_record.attempts - 1);
  END IF;

  -- Success! Mark verified
  UPDATE phone_verifications
  SET status = 'verified', verified_at = now()
  WHERE id = p_verification_id;

  -- Update candidate phone_verified flag
  UPDATE candidates
  SET phone_verified = true, phone_verified_at = now()
  WHERE user_id = v_user_id;

  RETURN json_build_object('success', true, 'message', 'Telefon numaranız doğrulandı');
END;
$$;

GRANT EXECUTE ON FUNCTION request_phone_otp TO authenticated;
GRANT EXECUTE ON FUNCTION verify_phone_otp TO authenticated;


-- ═══════════════════════════════════════════════════════════════
-- VERIFICATION
-- ═══════════════════════════════════════════════════════════════
-- SELECT request_phone_otp('05551234567');
-- SELECT verify_phone_otp(1, '123456');
