-- Migration 042: Competency system tables
-- Moves hardcoded yetkinlik data from profil-yetkinlik.js into Supabase.
-- Three tables: definitions (29 rows), role mapping (~200 rows), candidate self-assessment.
-- IMPORTANT: Run seed (042a) after this migration to populate reference data.

-- ═══════════════════════════════════════════════════════════════
-- 1. competency_definitions — 29 Korn Ferry competencies
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS competency_definitions (
  code varchar(4) PRIMARY KEY,                    -- cf, ce, it, co, ao, etc.
  name_tr text NOT NULL,                          -- Müşteri Odaklılık
  name_en text NOT NULL,                          -- Customer Focus
  tier char(1) NOT NULL DEFAULT 'A',              -- A (19), B (7), C (3)
  definition text NOT NULL,                       -- def: 1-cümle tanım
  why_critical text NOT NULL,                     -- why: neden kritik (retail bağlamlı)
  skilled text[] NOT NULL DEFAULT '{}',           -- 4-5 davranış maddesi
  less_skilled text[] NOT NULL DEFAULT '{}',      -- 4-5 davranış maddesi
  highly_skilled text[] NOT NULL DEFAULT '{}',    -- 3 madde
  overused text[] NOT NULL DEFAULT '{}',          -- 2-3 uyarı
  retail_example text NOT NULL DEFAULT '',        -- sahadan somut senaryo
  interview_question text NOT NULL DEFAULT '',    -- mülakat hazırlık sorusu
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE competency_definitions IS 'Korn Ferry competency framework — 29 retail-focused competencies';
COMMENT ON COLUMN competency_definitions.tier IS 'A=all levels, B=mid+senior, C=senior only';

-- ═══════════════════════════════════════════════════════════════
-- 2. role_competency_map — 34 roles × 5-11 competencies each
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS role_competency_map (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name text NOT NULL,                                -- Mağaza Müdürü, Kasiyer, etc.
  competency_code varchar(4) NOT NULL REFERENCES competency_definitions(code) ON DELETE CASCADE,
  sort_order int NOT NULL DEFAULT 0,                      -- position within the role
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Prevent duplicate role-competency pairs
CREATE UNIQUE INDEX IF NOT EXISTS idx_rcm_unique
  ON role_competency_map(role_name, competency_code);

-- Fast lookup by role
CREATE INDEX IF NOT EXISTS idx_rcm_role
  ON role_competency_map(role_name);

COMMENT ON TABLE role_competency_map IS 'Maps 34 retail roles to their required competencies';

-- ═══════════════════════════════════════════════════════════════
-- 3. candidate_competencies — candidate self-assessment
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS candidate_competencies (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  competency_code varchar(4) NOT NULL REFERENCES competency_definitions(code) ON DELETE CASCADE,
  rating varchar(10) NOT NULL DEFAULT 'growing',  -- 'strong' | 'growing'
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- One rating per candidate per competency
CREATE UNIQUE INDEX IF NOT EXISTS idx_cc_unique
  ON candidate_competencies(candidate_id, competency_code);

-- Fast lookup by candidate
CREATE INDEX IF NOT EXISTS idx_cc_candidate
  ON candidate_competencies(candidate_id);

COMMENT ON TABLE candidate_competencies IS 'Candidate self-assessment of competencies (strong/growing)';

-- ═══════════════════════════════════════════════════════════════
-- 4. RLS Policies
-- ═══════════════════════════════════════════════════════════════

-- competency_definitions: public read (reference data)
ALTER TABLE competency_definitions ENABLE ROW LEVEL SECURITY;

CREATE POLICY cd_public_read ON competency_definitions
  FOR SELECT USING (true);

-- role_competency_map: public read (reference data)
ALTER TABLE role_competency_map ENABLE ROW LEVEL SECURITY;

CREATE POLICY rcm_public_read ON role_competency_map
  FOR SELECT USING (true);

-- candidate_competencies: candidate own CRUD + employer read
ALTER TABLE candidate_competencies ENABLE ROW LEVEL SECURITY;

CREATE POLICY cc_select_own ON candidate_competencies
  FOR SELECT USING (candidate_id = get_my_candidate_id());

CREATE POLICY cc_insert_own ON candidate_competencies
  FOR INSERT WITH CHECK (candidate_id = get_my_candidate_id());

CREATE POLICY cc_update_own ON candidate_competencies
  FOR UPDATE USING (candidate_id = get_my_candidate_id())
  WITH CHECK (candidate_id = get_my_candidate_id());

CREATE POLICY cc_delete_own ON candidate_competencies
  FOR DELETE USING (candidate_id = get_my_candidate_id());

-- Employers can see competencies of visible candidates
CREATE POLICY cc_employer_read ON candidate_competencies
  FOR SELECT USING (
    is_employer()
    AND candidate_id IN (
      SELECT id FROM candidates
      WHERE is_active = true
      AND (profile_completed = true OR profile_completion_pct >= 45)
    )
  );

-- Admin read
CREATE POLICY cc_admin_read ON candidate_competencies
  FOR SELECT USING (is_admin());

-- ═══════════════════════════════════════════════════════════════
-- 5. Updated_at trigger for candidate_competencies
-- ═══════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION update_candidate_competencies_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_cc_updated_at
  BEFORE UPDATE ON candidate_competencies
  FOR EACH ROW
  EXECUTE FUNCTION update_candidate_competencies_updated_at();
