-- ============================================================
-- Migration 051: Transactional Email Phase 1
-- Date: 2026-03-20
-- Scope: email_outbox table + claim RPC + message trigger
-- Spec: docs/superpowers/specs/2026-03-20-transactional-email-phase1-design.md
-- ============================================================

-- 1. EMAIL OUTBOX TABLE
-- Single outbox for all transactional mails (welcome + message notification)

CREATE TABLE IF NOT EXISTS email_outbox (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dedupe_key            text NOT NULL UNIQUE,
  email_type            text NOT NULL CHECK (email_type IN (
                          'candidate_welcome', 'employer_welcome', 'new_message')),
  recipient_email       text NOT NULL,
  payload               jsonb NOT NULL DEFAULT '{}',
  status                text NOT NULL DEFAULT 'pending' CHECK (status IN (
                          'pending', 'processing', 'sent', 'failed', 'skipped')),
  source_table          text,
  source_id             text,
  attempt_count         int NOT NULL DEFAULT 0,
  last_error            text,
  processing_started_at timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now(),
  sent_at               timestamptz,
  next_retry_at         timestamptz DEFAULT now()
);

COMMENT ON TABLE email_outbox IS 'Phase 1 transactional email queue — all mail types flow through this table';
COMMENT ON COLUMN email_outbox.dedupe_key IS 'Deterministic key: candidate_welcome:{user_id}, employer_welcome:{user_id}, new_message:{employer_messages.id}. Also used as Resend Idempotency-Key header.';
COMMENT ON COLUMN email_outbox.status IS 'pending → processing → sent/failed. skipped = preference check failed at enqueue time.';

-- 2. PARTIAL INDEX FOR CLAIM QUERIES
-- Only indexes rows that the email-send processor needs to pick up

CREATE INDEX IF NOT EXISTS idx_outbox_claimable
  ON email_outbox (next_retry_at, created_at)
  WHERE status = 'pending';

-- 3. CLAIM BATCH FUNCTION
-- Atomically claims pending rows for processing.
-- Uses FOR UPDATE SKIP LOCKED to prevent double-claiming across concurrent workers.
-- Returns the claimed rows with status='processing'.

CREATE OR REPLACE FUNCTION claim_email_outbox_batch(p_limit int DEFAULT 10)
RETURNS SETOF email_outbox
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  WITH claimable AS (
    SELECT id
    FROM email_outbox
    WHERE status = 'pending'
      AND next_retry_at <= now()
    ORDER BY created_at
    LIMIT p_limit
    FOR UPDATE SKIP LOCKED
  )
  UPDATE email_outbox o
  SET status = 'processing',
      processing_started_at = now()
  FROM claimable c
  WHERE o.id = c.id
  RETURNING o.*;
END;
$$;

COMMENT ON FUNCTION claim_email_outbox_batch IS 'Atomically claim pending outbox rows. SKIP LOCKED ensures no row is claimed by two workers.';

-- 4. MESSAGE EMAIL ENQUEUE TRIGGER FUNCTION
-- Fires on employer_messages INSERT.
-- Checks candidate notify preference, derives sender_name, enqueues to outbox.
-- Phase 1: only candidates receive message notifications.

CREATE OR REPLACE FUNCTION enqueue_message_email()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate     record;
  v_hr            record;
  v_company_name  text;
  v_sender_name   text;
  v_preview       text;
BEGIN
  -- 1. Fetch candidate info
  SELECT full_name, email, notify_email_messages
  INTO v_candidate
  FROM candidates
  WHERE id = NEW.candidate_id;

  -- Candidate not found or no email — skip silently
  IF NOT FOUND OR v_candidate.email IS NULL THEN
    RETURN NEW;
  END IF;

  -- 2. Check notify preference — if false, enqueue as skipped
  IF v_candidate.notify_email_messages IS NOT TRUE THEN
    INSERT INTO email_outbox (
      dedupe_key, email_type, recipient_email, payload,
      status, source_table, source_id
    ) VALUES (
      'new_message:' || NEW.id::text,
      'new_message',
      v_candidate.email,
      '{}'::jsonb,
      'skipped',
      'employer_messages',
      NEW.id::text
    ) ON CONFLICT (dedupe_key) DO NOTHING;
    RETURN NEW;
  END IF;

  -- 3. Derive sender_name with 3-level fallback
  SELECT ad, soyad
  INTO v_hr
  FROM hr_profiles
  WHERE id = NEW.sender_id;

  v_sender_name := NULLIF(TRIM(
    COALESCE(v_hr.ad, '') || ' ' || COALESCE(v_hr.soyad, '')
  ), '');

  IF v_sender_name IS NULL THEN
    SELECT company_name INTO v_company_name
    FROM companies
    WHERE id = NEW.company_id;
    v_sender_name := v_company_name;
  END IF;

  v_sender_name := COALESCE(v_sender_name, 'HelloTalent İşveren Ekibi');

  -- 4. Message preview (first 100 chars)
  v_preview := LEFT(NEW.body, 100);

  -- 5. Enqueue
  INSERT INTO email_outbox (
    dedupe_key, email_type, recipient_email, payload,
    source_table, source_id
  ) VALUES (
    'new_message:' || NEW.id::text,
    'new_message',
    v_candidate.email,
    jsonb_build_object(
      'recipient_name', v_candidate.full_name,
      'sender_name',    v_sender_name,
      'message_preview', v_preview,
      'sent_at',        to_char(NEW.created_at, 'HH24:MI'),
      'cta_url',        'https://hellotalent.ai/giris.html',
      'settings_url',   'https://hellotalent.ai/giris.html'
    ),
    'employer_messages',
    NEW.id::text
  ) ON CONFLICT (dedupe_key) DO NOTHING;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION enqueue_message_email IS 'Enqueues new_message email to outbox on employer_messages INSERT. Phase 1: candidate-only, preference-gated.';

-- 5. TRIGGER ON employer_messages
-- Only fires on INSERT (not UPDATE/DELETE)

DROP TRIGGER IF EXISTS trg_employer_message_email ON employer_messages;

CREATE TRIGGER trg_employer_message_email
  AFTER INSERT ON employer_messages
  FOR EACH ROW
  WHEN (NEW.status = 'sent')
  EXECUTE FUNCTION enqueue_message_email();

-- ============================================================
-- NOTE: Cron schedules are NOT included in this migration.
-- They require environment-specific Edge Function URLs and
-- service role keys. See handoff.md for manual cron setup.
-- ============================================================
