-- ════════════════════════════════════════════════════════════════
-- Migration 052 — Candidate Message Replies
-- Date: 2026-03-21
-- Purpose: Allow candidates to reply to employer messages
-- Additive: new table + RPCs + RLS. No changes to employer_messages.
-- IMPORTANT: employer_messages.id is bigint, NOT uuid.
-- ════════════════════════════════════════════════════════════════

-- ──────────────────────────────────────────────
-- 1. Reply table
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS candidate_message_replies (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id  bigint NOT NULL REFERENCES employer_messages(id) ON DELETE CASCADE,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  body        text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 5000),
  read_at     timestamptz,   -- set when employer opens the thread
  created_at  timestamptz DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_cmr_message_id  ON candidate_message_replies(message_id);
CREATE INDEX IF NOT EXISTS idx_cmr_candidate_id ON candidate_message_replies(candidate_id);
CREATE INDEX IF NOT EXISTS idx_cmr_created_at   ON candidate_message_replies(created_at);

-- ──────────────────────────────────────────────
-- 2. RLS
-- ──────────────────────────────────────────────
ALTER TABLE candidate_message_replies ENABLE ROW LEVEL SECURITY;

-- Candidate can read their own replies
CREATE POLICY cmr_select_own ON candidate_message_replies
  FOR SELECT USING (candidate_id = get_my_candidate_id());

-- Candidate can insert replies only to messages addressed to them
CREATE POLICY cmr_insert_own ON candidate_message_replies
  FOR INSERT WITH CHECK (
    candidate_id = get_my_candidate_id()
    AND EXISTS (
      SELECT 1 FROM employer_messages em
       WHERE em.id = message_id
         AND em.candidate_id = get_my_candidate_id()
    )
  );

-- Employer can read replies to messages their company sent
CREATE POLICY cmr_employer_read ON candidate_message_replies
  FOR SELECT USING (
    is_employer()
    AND EXISTS (
      SELECT 1 FROM employer_messages em
       WHERE em.id = candidate_message_replies.message_id
         AND em.company_id = (
           SELECT hp.company_id FROM hr_profiles hp WHERE hp.id = auth.uid()
         )
    )
  );

-- Employer can update read_at on replies to their company's messages
CREATE POLICY cmr_employer_update_read ON candidate_message_replies
  FOR UPDATE USING (
    is_employer()
    AND EXISTS (
      SELECT 1 FROM employer_messages em
       WHERE em.id = candidate_message_replies.message_id
         AND em.company_id = (
           SELECT hp.company_id FROM hr_profiles hp WHERE hp.id = auth.uid()
         )
    )
  ) WITH CHECK (
    is_employer()
    AND EXISTS (
      SELECT 1 FROM employer_messages em
       WHERE em.id = candidate_message_replies.message_id
         AND em.company_id = (
           SELECT hp.company_id FROM hr_profiles hp WHERE hp.id = auth.uid()
         )
    )
  );

-- ──────────────────────────────────────────────
-- 3. RPC: send_candidate_reply
-- ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION send_candidate_reply(
  p_message_id bigint,
  p_body       text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
  v_msg_candidate_id bigint;
  v_reply_id bigint;
BEGIN
  SELECT c.id INTO v_candidate_id
    FROM candidates c WHERE c.user_id = auth.uid();
  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Aday profili bulunamadı.';
  END IF;

  SELECT em.candidate_id INTO v_msg_candidate_id
    FROM employer_messages em WHERE em.id = p_message_id;
  IF v_msg_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Mesaj bulunamadı.';
  END IF;
  IF v_msg_candidate_id <> v_candidate_id THEN
    RAISE EXCEPTION 'Bu mesaja yanıt verme yetkiniz yok.';
  END IF;

  IF p_body IS NULL OR char_length(trim(p_body)) < 1 THEN
    RAISE EXCEPTION 'Yanıt metni boş olamaz.';
  END IF;
  IF char_length(p_body) > 5000 THEN
    RAISE EXCEPTION 'Yanıt 5000 karakteri aşamaz.';
  END IF;

  INSERT INTO candidate_message_replies (message_id, candidate_id, body)
  VALUES (p_message_id, v_candidate_id, trim(p_body))
  RETURNING id INTO v_reply_id;

  RETURN v_reply_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION send_candidate_reply(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION send_candidate_reply(bigint, text) TO authenticated;

-- ──────────────────────────────────────────────
-- 4. RPC: get_message_thread
--    Returns the full thread: original employer
--    message + all candidate replies, with read
--    state, ordered chronologically.
-- ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION get_message_thread(p_message_id bigint)
RETURNS TABLE(
  item_id     bigint,
  sender      text,       -- 'employer' or 'candidate'
  body        text,
  created_at  timestamptz,
  read_at     timestamptz -- employer msg: read_at from employer_messages; reply: read_at from replies
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
  v_company_id   bigint;
  v_msg_candidate_id bigint;
  v_msg_company_id   bigint;
BEGIN
  SELECT c.id INTO v_candidate_id
    FROM candidates c WHERE c.user_id = auth.uid();
  SELECT hp.company_id INTO v_company_id
    FROM hr_profiles hp WHERE hp.id = auth.uid();

  SELECT em.candidate_id, em.company_id
    INTO v_msg_candidate_id, v_msg_company_id
    FROM employer_messages em WHERE em.id = p_message_id;

  IF v_msg_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Mesaj bulunamadı.';
  END IF;

  IF v_candidate_id IS NOT NULL AND v_candidate_id = v_msg_candidate_id THEN
    NULL; -- candidate owns this thread
  ELSIF v_company_id IS NOT NULL AND v_company_id = v_msg_company_id THEN
    NULL; -- employer from same company
  ELSE
    RAISE EXCEPTION 'Bu mesajın içeriğini görme yetkiniz yok.';
  END IF;

  RETURN QUERY
    -- Original employer message
    SELECT em.id AS item_id,
           'employer'::text AS sender,
           em.body,
           em.created_at,
           em.read_at
      FROM employer_messages em
     WHERE em.id = p_message_id

    UNION ALL

    -- Candidate replies
    SELECT cmr.id AS item_id,
           'candidate'::text AS sender,
           cmr.body,
           cmr.created_at,
           cmr.read_at
      FROM candidate_message_replies cmr
     WHERE cmr.message_id = p_message_id

    ORDER BY created_at ASC;
END;
$$;

REVOKE EXECUTE ON FUNCTION get_message_thread(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION get_message_thread(bigint) TO authenticated;

-- ──────────────────────────────────────────────
-- 5. RPC: mark_replies_read
--    Employer marks all unread candidate replies
--    for a specific message as read.
-- ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION mark_replies_read(p_message_id bigint)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_company_id bigint;
  v_msg_company_id bigint;
  v_count int;
BEGIN
  SELECT hp.company_id INTO v_company_id
    FROM hr_profiles hp WHERE hp.id = auth.uid();
  IF v_company_id IS NULL THEN
    RAISE EXCEPTION 'İşveren profili bulunamadı.';
  END IF;

  SELECT em.company_id INTO v_msg_company_id
    FROM employer_messages em WHERE em.id = p_message_id;
  IF v_msg_company_id IS NULL OR v_msg_company_id <> v_company_id THEN
    RAISE EXCEPTION 'Bu mesajın yanıtlarını işaretleme yetkiniz yok.';
  END IF;

  UPDATE candidate_message_replies
     SET read_at = now()
   WHERE message_id = p_message_id
     AND read_at IS NULL;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

REVOKE EXECUTE ON FUNCTION mark_replies_read(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION mark_replies_read(bigint) TO authenticated;

-- ──────────────────────────────────────────────
-- 6. Drop old get_message_replies if it exists
--    (replaced by get_message_thread)
-- ──────────────────────────────────────────────
DROP FUNCTION IF EXISTS get_message_replies(uuid);
