-- ════════════════════════════════════════════════════════════════
-- Migration 054 — Employer Follow-up Replies
-- Date: 2026-03-21
-- Purpose: Let employers reply back within existing message threads.
-- Additive: new table + RPC + updated get_message_thread.
-- ════════════════════════════════════════════════════════════════

-- ──────────────────────────────────────────────
-- 1. Employer follow-up reply table
-- ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS employer_message_replies (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id   bigint NOT NULL REFERENCES employer_messages(id) ON DELETE CASCADE,
  sender_id    uuid   NOT NULL REFERENCES auth.users(id),
  company_id   bigint NOT NULL REFERENCES companies(id),
  body         text   NOT NULL CHECK (char_length(body) BETWEEN 1 AND 5000),
  read_at      timestamptz,  -- set when candidate opens thread
  created_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_emr_message_id  ON employer_message_replies(message_id);
CREATE INDEX IF NOT EXISTS idx_emr_company_id  ON employer_message_replies(company_id);
CREATE INDEX IF NOT EXISTS idx_emr_created_at  ON employer_message_replies(created_at);

-- ──────────────────────────────────────────────
-- 2. RLS
-- ──────────────────────────────────────────────
ALTER TABLE employer_message_replies ENABLE ROW LEVEL SECURITY;

-- Employer can read their own company's follow-up replies
CREATE POLICY emr_employer_read ON employer_message_replies
  FOR SELECT USING (
    is_employer()
    AND company_id = (SELECT hp.company_id FROM hr_profiles hp WHERE hp.id = auth.uid())
  );

-- Employer can insert follow-up replies for their company's messages
CREATE POLICY emr_employer_insert ON employer_message_replies
  FOR INSERT WITH CHECK (
    is_employer()
    AND sender_id = auth.uid()
    AND company_id = (SELECT hp.company_id FROM hr_profiles hp WHERE hp.id = auth.uid())
    AND EXISTS (
      SELECT 1 FROM employer_messages em
       WHERE em.id = message_id
         AND em.company_id = company_id
    )
  );

-- Candidate can read employer follow-ups on messages sent to them
CREATE POLICY emr_candidate_read ON employer_message_replies
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM employer_messages em
       WHERE em.id = employer_message_replies.message_id
         AND em.candidate_id = get_my_candidate_id()
    )
  );

-- Candidate can update read_at on employer follow-ups sent to them
CREATE POLICY emr_candidate_update_read ON employer_message_replies
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM employer_messages em
       WHERE em.id = employer_message_replies.message_id
         AND em.candidate_id = get_my_candidate_id()
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM employer_messages em
       WHERE em.id = employer_message_replies.message_id
         AND em.candidate_id = get_my_candidate_id()
    )
  );

-- ──────────────────────────────────────────────
-- 3. RPC: send_employer_followup
-- ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION send_employer_followup(
  p_message_id bigint,
  p_body       text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_company_id bigint;
  v_msg_company_id bigint;
  v_reply_id bigint;
BEGIN
  SELECT hp.company_id INTO v_company_id
    FROM hr_profiles hp WHERE hp.id = auth.uid();
  IF v_company_id IS NULL THEN
    RAISE EXCEPTION 'İşveren profili bulunamadı.';
  END IF;

  SELECT em.company_id INTO v_msg_company_id
    FROM employer_messages em WHERE em.id = p_message_id;
  IF v_msg_company_id IS NULL THEN
    RAISE EXCEPTION 'Mesaj bulunamadı.';
  END IF;
  IF v_msg_company_id <> v_company_id THEN
    RAISE EXCEPTION 'Bu mesaja yanıt verme yetkiniz yok.';
  END IF;

  IF p_body IS NULL OR char_length(trim(p_body)) < 1 THEN
    RAISE EXCEPTION 'Yanıt metni boş olamaz.';
  END IF;
  IF char_length(p_body) > 5000 THEN
    RAISE EXCEPTION 'Yanıt 5000 karakteri aşamaz.';
  END IF;

  INSERT INTO employer_message_replies (message_id, sender_id, company_id, body)
  VALUES (p_message_id, auth.uid(), v_company_id, trim(p_body))
  RETURNING id INTO v_reply_id;

  RETURN v_reply_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION send_employer_followup(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION send_employer_followup(bigint, text) TO authenticated;

-- ──────────────────────────────────────────────
-- 4. RPC: mark_employer_replies_read
--    Candidate marks employer follow-ups as read.
-- ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION mark_employer_replies_read(p_message_id bigint)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
  v_msg_candidate_id bigint;
  v_count int;
BEGIN
  SELECT c.id INTO v_candidate_id
    FROM candidates c WHERE c.user_id = auth.uid();
  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Aday profili bulunamadı.';
  END IF;

  SELECT em.candidate_id INTO v_msg_candidate_id
    FROM employer_messages em WHERE em.id = p_message_id;
  IF v_msg_candidate_id IS NULL OR v_msg_candidate_id <> v_candidate_id THEN
    RAISE EXCEPTION 'Bu mesajın yanıtlarını işaretleme yetkiniz yok.';
  END IF;

  UPDATE employer_message_replies
     SET read_at = now()
   WHERE message_id = p_message_id
     AND read_at IS NULL;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

REVOKE EXECUTE ON FUNCTION mark_employer_replies_read(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION mark_employer_replies_read(bigint) TO authenticated;

-- ──────────────────────────────────────────────
-- 5. Update get_message_thread to include employer follow-ups
--    Now returns 3 sender types: 'employer', 'candidate', 'employer_followup'
-- ──────────────────────────────────────────────
CREATE OR REPLACE FUNCTION get_message_thread(p_message_id bigint)
RETURNS TABLE(
  item_id     bigint,
  sender      text,
  body        text,
  created_at  timestamptz,
  read_at     timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
  v_company_id   bigint;
  v_msg_candidate_id bigint;
  v_msg_company_id   bigint;
BEGIN
  SELECT c.id INTO v_candidate_id
    FROM candidates c WHERE c.user_id = auth.uid();
  SELECT hp.company_id INTO v_company_id
    FROM hr_profiles hp WHERE hp.id = auth.uid();

  SELECT em.candidate_id, em.company_id
    INTO v_msg_candidate_id, v_msg_company_id
    FROM employer_messages em WHERE em.id = p_message_id;

  IF v_msg_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Mesaj bulunamadı.';
  END IF;

  IF v_candidate_id IS NOT NULL AND v_candidate_id = v_msg_candidate_id THEN
    NULL;
  ELSIF v_company_id IS NOT NULL AND v_company_id = v_msg_company_id THEN
    NULL;
  ELSE
    RAISE EXCEPTION 'Bu mesajın içeriğini görme yetkiniz yok.';
  END IF;

  RETURN QUERY
    -- Original employer message
    SELECT em.id AS item_id,
           'employer'::text AS sender,
           em.body,
           em.created_at,
           em.read_at
      FROM employer_messages em
     WHERE em.id = p_message_id

    UNION ALL

    -- Candidate replies
    SELECT cmr.id AS item_id,
           'candidate'::text AS sender,
           cmr.body,
           cmr.created_at,
           cmr.read_at
      FROM candidate_message_replies cmr
     WHERE cmr.message_id = p_message_id

    UNION ALL

    -- Employer follow-up replies
    SELECT emr.id AS item_id,
           'employer'::text AS sender,
           emr.body,
           emr.created_at,
           emr.read_at
      FROM employer_message_replies emr
     WHERE emr.message_id = p_message_id

    ORDER BY created_at ASC;
END;
$$;
