-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 058 — Coach System (Koclardan Ogren)
-- Date: 2026-03-22
-- Type: SCHEMA + RLS + RPC + TRIGGER
-- Purpose: Invite-only coach content system for Mulakat Kocu feed
-- Dependencies: admin_users (014), candidates (001), is_admin() (014),
--               get_my_candidate_id() (001), email_outbox (051)
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- 1. TABLES
-- ═══════════════════════════════════════════════════════════════════════════


-- ── 1a. coach_invites ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS coach_invites (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           text NOT NULL,
  display_name    text,
  invited_by      uuid NOT NULL REFERENCES admin_users(id),
  status          text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','accepted','expired','revoked')),
  token           uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  expires_at      timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  accepted_at     timestamptz,
  revoked_at      timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_coach_invites_token
  ON coach_invites(token);

CREATE INDEX IF NOT EXISTS idx_coach_invites_email
  ON coach_invites(email);

-- Prevent duplicate pending invitations for same email
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE tablename = 'coach_invites'
      AND indexname = 'idx_coach_invites_pending_unique'
  ) THEN
    CREATE UNIQUE INDEX idx_coach_invites_pending_unique
      ON coach_invites(email)
      WHERE status = 'pending';
  END IF;
END
$$;


-- ── 1b. coach_profiles ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS coach_profiles (
  id              uuid PRIMARY KEY REFERENCES auth.users(id),
  invite_id       bigint NOT NULL REFERENCES coach_invites(id),
  display_name    text NOT NULL,
  title           text,
  avatar_url      text,
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now()
);


-- ── 1c. coach_posts ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS coach_posts (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id        uuid NOT NULL REFERENCES coach_profiles(id),
  title           text NOT NULL,
  excerpt         text,
  body            text NOT NULL,
  category        text NOT NULL
                    CHECK (category IN ('mulakat_ipucu','yetkinlik_rehberi','kariyer_hikaye','sektor_analiz')),
  related_role    text,
  related_competency_code text,
  status          text NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft','submitted','changes_requested','published','archived','rejected')),
  admin_note      text,
  like_count      integer NOT NULL DEFAULT 0,
  published_at    timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_coach_posts_feed
  ON coach_posts(status, published_at DESC)
  WHERE status = 'published';

CREATE INDEX IF NOT EXISTS idx_coach_posts_coach
  ON coach_posts(coach_id);

CREATE INDEX IF NOT EXISTS idx_coach_posts_status
  ON coach_posts(status);


-- ── 1d. coach_post_likes ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS coach_post_likes (
  candidate_id    bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  post_id         bigint NOT NULL REFERENCES coach_posts(id) ON DELETE CASCADE,
  created_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (candidate_id, post_id)
);


-- ═══════════════════════════════════════════════════════════════════════════
-- 2. TRIGGERS
-- ═══════════════════════════════════════════════════════════════════════════

-- Reuse standard updated_at trigger function if it exists, else create
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_coach_posts_updated_at ON coach_posts;
CREATE TRIGGER trg_coach_posts_updated_at
  BEFORE UPDATE ON coach_posts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ═══════════════════════════════════════════════════════════════════════════
-- 3. RLS POLICIES
-- ═══════════════════════════════════════════════════════════════════════════


-- ── 3a. coach_invites — admin only ──────────────────────────────────────

ALTER TABLE coach_invites ENABLE ROW LEVEL SECURITY;

CREATE POLICY coach_invites_admin ON coach_invites
  FOR ALL USING (is_admin());

-- Coaches can read their own invite (for studio acceptance check)
CREATE POLICY coach_invites_own_read ON coach_invites
  FOR SELECT USING (
    email = (SELECT email FROM auth.users WHERE id = auth.uid())
  );


-- ── 3b. coach_profiles ─────────────────────────────────────────────────

ALTER TABLE coach_profiles ENABLE ROW LEVEL SECURITY;

-- Coach reads own
CREATE POLICY coach_profiles_own_read ON coach_profiles
  FOR SELECT USING (id = auth.uid());

-- Coach updates own (display_name, title, avatar_url)
CREATE POLICY coach_profiles_own_update ON coach_profiles
  FOR UPDATE USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- Admin full CRUD
CREATE POLICY coach_profiles_admin ON coach_profiles
  FOR ALL USING (is_admin());

-- Authenticated users can read active coach profiles (for feed display)
CREATE POLICY coach_profiles_authenticated_read ON coach_profiles
  FOR SELECT USING (
    is_active = true
    AND auth.uid() IS NOT NULL
  );


-- ── 3c. coach_posts ────────────────────────────────────────────────────

ALTER TABLE coach_posts ENABLE ROW LEVEL SECURITY;

-- Coach reads own posts (any status)
CREATE POLICY coach_posts_coach_read ON coach_posts
  FOR SELECT USING (
    coach_id = auth.uid()
  );

-- Coach inserts own posts
CREATE POLICY coach_posts_coach_insert ON coach_posts
  FOR INSERT WITH CHECK (
    coach_id = auth.uid()
    AND EXISTS (SELECT 1 FROM coach_profiles WHERE id = auth.uid() AND is_active = true)
  );

-- Coach updates own draft/changes_requested posts
CREATE POLICY coach_posts_coach_update ON coach_posts
  FOR UPDATE USING (
    coach_id = auth.uid()
    AND status IN ('draft', 'changes_requested')
  ) WITH CHECK (
    coach_id = auth.uid()
  );

-- Admin full CRUD
CREATE POLICY coach_posts_admin ON coach_posts
  FOR ALL USING (is_admin());

-- Authenticated candidates can read published posts from active coaches
CREATE POLICY coach_posts_published_read ON coach_posts
  FOR SELECT USING (
    status = 'published'
    AND auth.uid() IS NOT NULL
    AND EXISTS (SELECT 1 FROM coach_profiles cp WHERE cp.id = coach_posts.coach_id AND cp.is_active = true)
  );


-- ── 3d. coach_post_likes ───────────────────────────────────────────────

ALTER TABLE coach_post_likes ENABLE ROW LEVEL SECURITY;

-- Candidate reads own likes
CREATE POLICY coach_post_likes_own_read ON coach_post_likes
  FOR SELECT USING (candidate_id = get_my_candidate_id());

-- Candidate inserts own like
CREATE POLICY coach_post_likes_own_insert ON coach_post_likes
  FOR INSERT WITH CHECK (candidate_id = get_my_candidate_id());

-- Candidate deletes own like
CREATE POLICY coach_post_likes_own_delete ON coach_post_likes
  FOR DELETE USING (candidate_id = get_my_candidate_id());

-- Admin can read all (analytics)
CREATE POLICY coach_post_likes_admin ON coach_post_likes
  FOR ALL USING (is_admin());


-- ═══════════════════════════════════════════════════════════════════════════
-- 4. RPC FUNCTIONS
-- ═══════════════════════════════════════════════════════════════════════════


-- ── 4a. accept_coach_invite ─────────────────────────────────────────────

CREATE OR REPLACE FUNCTION accept_coach_invite(p_token uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_user_email text;
  v_invite coach_invites%ROWTYPE;
  v_profile coach_profiles%ROWTYPE;
BEGIN
  -- Derive authenticated user
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Oturum acilmamis.';
  END IF;

  -- Get user email from auth.users
  SELECT email INTO v_user_email FROM auth.users WHERE id = v_user_id;
  IF v_user_email IS NULL THEN
    RAISE EXCEPTION 'Kullanici e-postasi bulunamadi.';
  END IF;

  -- Check if already a coach
  IF EXISTS (SELECT 1 FROM coach_profiles WHERE id = v_user_id) THEN
    SELECT * INTO v_profile FROM coach_profiles WHERE id = v_user_id;
    RETURN row_to_json(v_profile);
  END IF;

  -- Find and validate invite
  SELECT * INTO v_invite FROM coach_invites WHERE token = p_token;
  IF v_invite.id IS NULL THEN
    RAISE EXCEPTION 'Gecersiz davet baglantisi.';
  END IF;

  IF v_invite.status <> 'pending' THEN
    RAISE EXCEPTION 'Bu davet artik gecerli degil (durum: %).', v_invite.status;
  END IF;

  IF v_invite.expires_at < now() THEN
    -- Auto-expire
    UPDATE coach_invites SET status = 'expired' WHERE id = v_invite.id;
    RAISE EXCEPTION 'Davet suresi dolmus.';
  END IF;

  -- SECURITY: Email must match invite
  IF lower(trim(v_user_email)) <> lower(trim(v_invite.email)) THEN
    RAISE EXCEPTION 'Bu davet farkli bir e-posta adresine gonderilmis. Lutfen dogru hesapla giris yapin.';
  END IF;

  -- Create coach profile
  INSERT INTO coach_profiles (id, invite_id, display_name)
  VALUES (v_user_id, v_invite.id, COALESCE(v_invite.display_name, split_part(v_user_email, '@', 1)))
  RETURNING * INTO v_profile;

  -- Mark invite accepted
  UPDATE coach_invites
  SET status = 'accepted', accepted_at = now()
  WHERE id = v_invite.id;

  RETURN row_to_json(v_profile);
END;
$$;

REVOKE EXECUTE ON FUNCTION accept_coach_invite(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION accept_coach_invite(uuid) TO authenticated;


-- ── 4b. toggle_coach_post_like ──────────────────────────────────────────

CREATE OR REPLACE FUNCTION toggle_coach_post_like(p_post_id bigint)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
  v_exists boolean;
  v_new_count integer;
BEGIN
  -- Derive candidate
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Aday profili bulunamadi.';
  END IF;

  -- Verify post is published
  IF NOT EXISTS (SELECT 1 FROM coach_posts WHERE id = p_post_id AND status = 'published') THEN
    RAISE EXCEPTION 'Yazi bulunamadi.';
  END IF;

  -- Check existing like
  SELECT EXISTS (
    SELECT 1 FROM coach_post_likes
    WHERE candidate_id = v_candidate_id AND post_id = p_post_id
  ) INTO v_exists;

  IF v_exists THEN
    -- Remove like
    DELETE FROM coach_post_likes
    WHERE candidate_id = v_candidate_id AND post_id = p_post_id;

    UPDATE coach_posts SET like_count = GREATEST(like_count - 1, 0)
    WHERE id = p_post_id
    RETURNING like_count INTO v_new_count;
  ELSE
    -- Add like
    INSERT INTO coach_post_likes (candidate_id, post_id)
    VALUES (v_candidate_id, p_post_id);

    UPDATE coach_posts SET like_count = like_count + 1
    WHERE id = p_post_id
    RETURNING like_count INTO v_new_count;
  END IF;

  RETURN v_new_count;
END;
$$;

REVOKE EXECUTE ON FUNCTION toggle_coach_post_like(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION toggle_coach_post_like(bigint) TO authenticated;


-- ── 4c. enqueue_coach_invite_email (trigger function) ───────────────────
-- Enqueues invite email into existing email_outbox pipeline on coach_invites INSERT

CREATE OR REPLACE FUNCTION enqueue_coach_invite_email()
RETURNS trigger AS $$
BEGIN
  IF NEW.status = 'pending' THEN
    INSERT INTO email_outbox (
      email_type,
      recipient_email,
      template_data,
      dedupe_key
    ) VALUES (
      'coach_invite',
      NEW.email,
      jsonb_build_object(
        'display_name', COALESCE(NEW.display_name, split_part(NEW.email, '@', 1)),
        'invite_url', 'https://hellotalent.ai/coach-studio.html?token=' || NEW.token::text,
        'expires_at', NEW.expires_at::text
      ),
      'coach_invite:' || NEW.id::text
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_coach_invite_email ON coach_invites;
CREATE TRIGGER trg_coach_invite_email
  AFTER INSERT ON coach_invites
  FOR EACH ROW EXECUTE FUNCTION enqueue_coach_invite_email();


-- ═══════════════════════════════════════════════════════════════════════════
-- 5. COMMENTS
-- ═══════════════════════════════════════════════════════════════════════════

COMMENT ON TABLE coach_invites IS 'Admin-created invitations for coaches. Token-based acceptance with email verification.';
COMMENT ON TABLE coach_profiles IS 'Accepted coaches with auth.users FK. Invite-only access.';
COMMENT ON TABLE coach_posts IS 'Coach-authored content. Workflow: draft→submitted→published. Feed visible to authenticated candidates.';
COMMENT ON TABLE coach_post_likes IS 'Privacy-safe likes. Candidate sees own + total count only.';
COMMENT ON FUNCTION accept_coach_invite IS 'Validates token + email match, creates coach profile. SECURITY DEFINER.';
COMMENT ON FUNCTION toggle_coach_post_like IS 'Atomic like/unlike with denormalized count update. SECURITY DEFINER.';
