#!/usr/bin/env bash
# Weekly maintenance scan — maintenance-agent weekly routine
# Launchd trigger: her Pazar saat 09:00

set -e

REPO=~/Downloads/Hellotalent
cd "$REPO"

TS=$(date +%Y%m%d-%H%M%S)
REPORT="$REPO/.claude/agent-memory/maintenance-reports/weekly-$TS.md"
mkdir -p "$(dirname "$REPORT")"

echo "# Weekly Maintenance Report — $(date +%Y-%m-%d)" > "$REPORT"
echo "" >> "$REPORT"
echo "## Generated by launchd (cron equivalent) — maintenance-agent scope" >> "$REPORT"
echo "" >> "$REPORT"

# Worktree + node_modules + archive exclude pattern (grep + find)
GREP_EXCLUDE="--exclude-dir=.claude/worktrees --exclude-dir=node_modules --exclude-dir=_archive --exclude-dir=archive --exclude-dir=.git"
FIND_EXCLUDE='-not -path "*/.claude/worktrees/*" -not -path "*/node_modules/*" -not -path "*/_archive*/*" -not -path "*/archive*/*"'

# 1. Dead code grep
echo "## Dead Code / TODO / FIXME" >> "$REPORT"
TODO_COUNT=$(grep -rn $GREP_EXCLUDE 'TODO\|FIXME\|XXX\|HACK' --include='*.js' --include='*.html' --include='*.css' . 2>/dev/null | wc -l | tr -d ' ')
echo "- TODO/FIXME/XXX/HACK count: $TODO_COUNT" >> "$REPORT"
echo "" >> "$REPORT"

# 2. Large files (6300+ line profil.html early warning)
echo "## Large Files (>3000 lines)" >> "$REPORT"
find . -type f \( -name "*.html" -o -name "*.js" \) -not -path "*/.claude/worktrees/*" -not -path "*/node_modules/*" -not -path "*/_archive*/*" -not -path "*/archive*/*" 2>/dev/null | while read f; do
  lines=$(wc -l < "$f" 2>/dev/null | tr -d ' ')
  if [ "$lines" -gt 3000 ]; then
    echo "- $f: $lines lines" >> "$REPORT"
  fi
done
echo "" >> "$REPORT"

# 3. Deprecated markers
echo "## Deprecated Code" >> "$REPORT"
DEPRECATED=$(grep -rn $GREP_EXCLUDE '@deprecated\|DEPRECATED' --include='*.js' --include='*.html' . 2>/dev/null | wc -l | tr -d ' ')
echo "- Deprecated markers: $DEPRECATED" >> "$REPORT"
echo "" >> "$REPORT"

# 4. Console.log in production (should be console.error or console.warn only)
echo "## Console.log Leaks (prod forbidden)" >> "$REPORT"
CONSOLE_LOG=$(grep -rn $GREP_EXCLUDE 'console\.log' --include='*.js' --include='*.html' . 2>/dev/null | grep -v '//.*console.log' | wc -l | tr -d ' ')
echo "- console.log occurrences: $CONSOLE_LOG" >> "$REPORT"
echo "" >> "$REPORT"

# 5. RLS guard (supabase/migrations)
echo "## RLS Guard Check" >> "$REPORT"
if [ -f scripts/check-rls-guard.sh ]; then
  bash scripts/check-rls-guard.sh >> "$REPORT" 2>&1 || true
fi
echo "" >> "$REPORT"

# 6. Git repo health
echo "## Git Health" >> "$REPORT"
COMMITS_WEEK=$(git log --since='7 days ago' --oneline 2>/dev/null | wc -l | tr -d ' ')
echo "- Commits last 7 days: $COMMITS_WEEK" >> "$REPORT"
UNCOMMITTED=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
echo "- Uncommitted changes: $UNCOMMITTED" >> "$REPORT"
echo "" >> "$REPORT"

# 7. Agent Memory cleanup check
echo "## Agent Memory" >> "$REPORT"
MEM_SIZE=$(du -sh .claude/agent-memory 2>/dev/null | awk '{print $1}')
echo "- .claude/agent-memory size: $MEM_SIZE" >> "$REPORT"
OLD_BACKUPS=$(find .claude/agent-memory/teams-backups -name "*.tar.gz" -mtime +7 2>/dev/null | wc -l | tr -d ' ')
echo "- Teams backups >7 days (auto-clean): $OLD_BACKUPS" >> "$REPORT"
echo "" >> "$REPORT"

# Cleanup old teams backups
find .claude/agent-memory/teams-backups -name "*.tar.gz" -mtime +7 -delete 2>/dev/null || true

# 8. Pending approvals + rules count
echo "## Pending Queues" >> "$REPORT"
if [ -f .claude/agent-memory/pending-approvals.md ]; then
  PENDING_APPROVAL=$(grep -c "^## A[0-9]" .claude/agent-memory/pending-approvals.md 2>/dev/null || echo 0)
  echo "- Pending approvals: $PENDING_APPROVAL" >> "$REPORT"
fi
if [ -f .claude/agent-memory/pending-rules.md ]; then
  PENDING_RULE=$(grep -c "^## PR[0-9]" .claude/agent-memory/pending-rules.md 2>/dev/null || echo 0)
  echo "- Pending rules: $PENDING_RULE" >> "$REPORT"
fi

# 9. KPI snapshot (Reform v3.4)
echo "" >> "$REPORT"
echo "## KPI Snapshot" >> "$REPORT"
if [ -x scripts/kpi-snapshot.sh ]; then
  bash scripts/kpi-snapshot.sh 2>&1 | tail -10 >> "$REPORT"
fi

# 10. /si:status auto (memory health)
echo "" >> "$REPORT"
echo "## /si:status (auto)" >> "$REPORT"
if [ -x scripts/si-status-auto.sh ]; then
  bash scripts/si-status-auto.sh --brief 2>&1 >> "$REPORT"
fi

# 11. SELF-AUDIT ledger drift check
echo "" >> "$REPORT"
echo "## SELF-AUDIT Drift Check" >> "$REPORT"
if [ -f docs/SELF-AUDIT.md ]; then
  STALE=$(grep -c "📝 PENDING" docs/SELF-AUDIT.md 2>/dev/null || echo 0)
  VERIFIED=$(grep -c "✅" docs/SELF-AUDIT.md 2>/dev/null || echo 0)
  echo "- SELF-AUDIT entries: $VERIFIED verified | $STALE pending" >> "$REPORT"
fi

# 12. Worktree cleanup dry-run (Reform 16 May Öneri 8)
echo "" >> "$REPORT"
echo "## Worktree Cleanup (dry-run)" >> "$REPORT"
if [ -x scripts/worktree-cleanup.sh ]; then
  bash scripts/worktree-cleanup.sh 2>&1 | tail -15 >> "$REPORT"
  echo "" >> "$REPORT"
  echo "_Uygulamak için: \`bash scripts/worktree-cleanup.sh --apply\` (manuel, Tuna kararı)_" >> "$REPORT"
fi

echo "" >> "$REPORT"
echo "---" >> "$REPORT"
echo "End of weekly scan. Next run: next Sunday 09:00." >> "$REPORT"

echo "[weekly-maintenance] Report: $REPORT"
cat "$REPORT"

exit 0
