-- Studio Phase 3 — Badge System Foundation
-- Date: 2026-03-26
-- Type: SCHEMA + RLS + RPC + SEED
-- Purpose:
--   1. badge_definitions table
--   2. candidate_badges table
--   3. evaluate_candidate_badges() issuance RPC
--   4. Updated complete_studio_module() with badge trigger
--   5. Seeded V1 badge definitions (6 badges)

-- ═══════════════════════════════════════════════
-- 1. BADGE DEFINITIONS
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS badge_definitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  icon_key text NOT NULL DEFAULT 'star',
  badge_tier text NOT NULL DEFAULT 'base',
  rule_type text NOT NULL,
  rule_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order int DEFAULT 0,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE badge_definitions ADD CONSTRAINT badge_definitions_category_check
  CHECK (category IN ('studio', 'performans', 'bilgiler', 'yetenek'));

ALTER TABLE badge_definitions ADD CONSTRAINT badge_definitions_tier_check
  CHECK (badge_tier IN ('base', 'milestone', 'advanced'));

ALTER TABLE badge_definitions ADD CONSTRAINT badge_definitions_rule_type_check
  CHECK (rule_type IN ('module_complete_count', 'section_complete', 'total_complete_count'));

ALTER TABLE badge_definitions ADD CONSTRAINT badge_definitions_status_check
  CHECK (status IN ('active', 'inactive'));

-- RLS: everyone reads active definitions, admin writes
ALTER TABLE badge_definitions ENABLE ROW LEVEL SECURITY;

CREATE POLICY badge_definitions_read_active ON badge_definitions
  FOR SELECT TO authenticated
  USING (status = 'active');

DROP POLICY IF EXISTS badge_definitions_admin_all ON badge_definitions;
CREATE POLICY badge_definitions_admin_all ON badge_definitions
  FOR ALL TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_badge_definitions_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_badge_definitions_updated_at ON badge_definitions;
CREATE TRIGGER trg_badge_definitions_updated_at
  BEFORE UPDATE ON badge_definitions
  FOR EACH ROW EXECUTE FUNCTION update_badge_definitions_updated_at();


-- ═══════════════════════════════════════════════
-- 2. CANDIDATE BADGES
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS candidate_badges (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  badge_id bigint NOT NULL REFERENCES badge_definitions(id) ON DELETE CASCADE,
  awarded_at timestamptz DEFAULT now(),
  award_reason text,
  metadata jsonb,
  UNIQUE (candidate_id, badge_id)
);

CREATE INDEX IF NOT EXISTS idx_candidate_badges_candidate ON candidate_badges (candidate_id);

-- RLS: candidates read own badges only
ALTER TABLE candidate_badges ENABLE ROW LEVEL SECURITY;

CREATE POLICY candidate_badges_select_own ON candidate_badges
  FOR SELECT TO authenticated
  USING (candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid()));

-- No direct INSERT — must go through evaluation RPC


-- ═══════════════════════════════════════════════
-- 3. BADGE EVALUATION RPC
-- Idempotent: ON CONFLICT DO NOTHING.
-- Called after every module completion.
-- Checks all active badge rules against candidate's current progress.
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION evaluate_candidate_badges(p_candidate_id bigint)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_badge RECORD;
  v_awarded int := 0;
  v_count int;
  v_section_total int;
  v_section_completed int;
BEGIN
  FOR v_badge IN
    SELECT id, slug, rule_type, rule_config, category
    FROM badge_definitions
    WHERE status = 'active'
      AND id NOT IN (SELECT badge_id FROM candidate_badges WHERE candidate_id = p_candidate_id)
  LOOP
    -- ── module_complete_count: candidate completed N modules in a specific section (or any) ──
    IF v_badge.rule_type = 'module_complete_count' THEN
      IF v_badge.rule_config ? 'section' THEN
        SELECT count(*) INTO v_count
        FROM candidate_studio_progress csp
        JOIN studio_modules sm ON sm.id = csp.module_id
        WHERE csp.candidate_id = p_candidate_id
          AND csp.status = 'completed'
          AND sm.section = v_badge.rule_config->>'section';
      ELSE
        SELECT count(*) INTO v_count
        FROM candidate_studio_progress
        WHERE candidate_id = p_candidate_id AND status = 'completed';
      END IF;

      IF v_count >= COALESCE((v_badge.rule_config->>'min_count')::int, 1) THEN
        INSERT INTO candidate_badges (candidate_id, badge_id, award_reason)
        VALUES (p_candidate_id, v_badge.id, v_badge.rule_type || ':' || v_count)
        ON CONFLICT (candidate_id, badge_id) DO NOTHING;
        v_awarded := v_awarded + 1;
      END IF;

    -- ── section_complete: all published modules in a section completed ──
    ELSIF v_badge.rule_type = 'section_complete' THEN
      SELECT count(*) INTO v_section_total
      FROM studio_modules
      WHERE section = v_badge.rule_config->>'section' AND status = 'published';

      IF v_section_total > 0 THEN
        SELECT count(*) INTO v_section_completed
        FROM candidate_studio_progress csp
        JOIN studio_modules sm ON sm.id = csp.module_id
        WHERE csp.candidate_id = p_candidate_id
          AND csp.status = 'completed'
          AND sm.section = v_badge.rule_config->>'section'
          AND sm.status = 'published';

        IF v_section_completed >= v_section_total THEN
          INSERT INTO candidate_badges (candidate_id, badge_id, award_reason)
          VALUES (p_candidate_id, v_badge.id, 'section_complete:' || (v_badge.rule_config->>'section') || ':' || v_section_completed || '/' || v_section_total)
          ON CONFLICT (candidate_id, badge_id) DO NOTHING;
          v_awarded := v_awarded + 1;
        END IF;
      END IF;

    -- ── total_complete_count: N modules completed regardless of section ──
    ELSIF v_badge.rule_type = 'total_complete_count' THEN
      SELECT count(*) INTO v_count
      FROM candidate_studio_progress
      WHERE candidate_id = p_candidate_id AND status = 'completed';

      IF v_count >= COALESCE((v_badge.rule_config->>'min_count')::int, 1) THEN
        INSERT INTO candidate_badges (candidate_id, badge_id, award_reason)
        VALUES (p_candidate_id, v_badge.id, 'total_complete:' || v_count)
        ON CONFLICT (candidate_id, badge_id) DO NOTHING;
        v_awarded := v_awarded + 1;
      END IF;
    END IF;
  END LOOP;

  RETURN v_awarded;
END;
$$;

REVOKE EXECUTE ON FUNCTION evaluate_candidate_badges(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION evaluate_candidate_badges(bigint) TO authenticated;


-- ═══════════════════════════════════════════════
-- 4. UPDATE complete_studio_module TO TRIGGER BADGE EVALUATION
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION complete_studio_module(p_module_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Aday profili bulunamadi.';
  END IF;

  INSERT INTO candidate_studio_progress (candidate_id, module_id, status, progress_pct, completed_at)
  VALUES (v_candidate_id, p_module_id, 'completed', 100, now())
  ON CONFLICT (candidate_id, module_id)
  DO UPDATE SET status = 'completed', progress_pct = 100, completed_at = now(), last_viewed_at = now();

  -- Evaluate and award any newly-earned badges
  PERFORM evaluate_candidate_badges(v_candidate_id);
END;
$$;

REVOKE EXECUTE ON FUNCTION complete_studio_module(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION complete_studio_module(bigint) TO authenticated;


-- ═══════════════════════════════════════════════
-- 5. SEED V1 BADGE DEFINITIONS (6 badges)
-- ═══════════════════════════════════════════════

INSERT INTO badge_definitions (slug, title, description, category, icon_key, badge_tier, rule_type, rule_config, sort_order)
VALUES
  ('studyo-ilk-adim',
   'İlk Adım',
   'İlk Stüdyo modülünü tamamladın. Öğrenme yolculuğun başladı.',
   'studio', 'rocket', 'base',
   'total_complete_count', '{"min_count": 1}'::jsonb, 1),

  ('performans-baslangic',
   'Performans Başlangıç',
   'İlk Performans modülünü tamamladın. Rakamları anlamaya başladın.',
   'performans', 'chart', 'base',
   'module_complete_count', '{"section": "performans", "min_count": 1}'::jsonb, 2),

  ('bilgiler-baslangic',
   'Platform Bilgisi',
   'İlk HelloTalent''ten Bilgiler modülünü tamamladın. Platformu daha iyi tanıyorsun.',
   'bilgiler', 'lightbulb', 'base',
   'module_complete_count', '{"section": "bilgiler", "min_count": 1}'::jsonb, 3),

  ('studyo-disiplini',
   'Stüdyo Disiplini',
   'En az 3 Stüdyo modülü tamamladın. Düzenli öğrenme alışkanlığın oluşuyor.',
   'studio', 'target', 'milestone',
   'total_complete_count', '{"min_count": 3}'::jsonb, 4),

  ('performans-temelleri',
   'KPI Uzmanı',
   'Tüm Performans modüllerini tamamladın. Mağaza rakamlarını artık okuyabilirsin.',
   'performans', 'trophy', 'advanced',
   'section_complete', '{"section": "performans"}'::jsonb, 5),

  ('studyo-ustalik-yolu',
   'Ustalık Yolu',
   'Tüm Stüdyo modüllerini tamamladın. Kariyerinde fark yaratmaya hazırsın.',
   'studio', 'crown', 'advanced',
   'total_complete_count', '{"min_count": 8}'::jsonb, 6);
