-- Studio Phase 4 — Journal persistence + Yetenek progress bridge
-- Date: 2026-03-26
-- Type: SCHEMA + RLS + RPC
-- Purpose:
--   1. candidate_studio_journals — STAR+T drafts persisted to DB
--   2. candidate_yetenek_progress — practice truth signals
--   3. RPCs for upsert operations

-- ═══════════════════════════════════════════════
-- 1. CANDIDATE STUDIO JOURNALS
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS candidate_studio_journals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  context_type text NOT NULL DEFAULT 'yetenek_question',
  role_key text,
  competency_code text NOT NULL,
  question_hash text NOT NULL,
  question_text text,
  situation_text text DEFAULT '',
  task_text text DEFAULT '',
  action_text text DEFAULT '',
  result_text text DEFAULT '',
  takeaway_text text DEFAULT '',
  status text NOT NULL DEFAULT 'draft',
  last_edited_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (candidate_id, competency_code, question_hash)
);

ALTER TABLE candidate_studio_journals ADD CONSTRAINT csj_context_type_check
  CHECK (context_type IN ('yetenek_question', 'studio_module_note'));

ALTER TABLE candidate_studio_journals ADD CONSTRAINT csj_status_check
  CHECK (status IN ('draft', 'completed'));

CREATE INDEX IF NOT EXISTS idx_csj_candidate ON candidate_studio_journals (candidate_id);
CREATE INDEX IF NOT EXISTS idx_csj_candidate_comp ON candidate_studio_journals (candidate_id, competency_code);

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_csj_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_csj_updated_at ON candidate_studio_journals;
CREATE TRIGGER trg_csj_updated_at
  BEFORE UPDATE ON candidate_studio_journals
  FOR EACH ROW EXECUTE FUNCTION update_csj_updated_at();

-- RLS: candidates read/write own journals only
ALTER TABLE candidate_studio_journals ENABLE ROW LEVEL SECURITY;

CREATE POLICY csj_select_own ON candidate_studio_journals
  FOR SELECT TO authenticated
  USING (candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid()));

-- No direct INSERT/UPDATE — use RPC


-- ═══════════════════════════════════════════════
-- 2. CANDIDATE YETENEK PROGRESS
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS candidate_yetenek_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  role_key text NOT NULL,
  competency_code text NOT NULL,
  status text NOT NULL DEFAULT 'started',
  practice_count int DEFAULT 0,
  questions_answered int DEFAULT 0,
  last_practiced_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (candidate_id, role_key, competency_code)
);

ALTER TABLE candidate_yetenek_progress ADD CONSTRAINT cyp_status_check
  CHECK (status IN ('started', 'practiced', 'completed'));

CREATE INDEX IF NOT EXISTS idx_cyp_candidate ON candidate_yetenek_progress (candidate_id);

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_cyp_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_cyp_updated_at ON candidate_yetenek_progress;
CREATE TRIGGER trg_cyp_updated_at
  BEFORE UPDATE ON candidate_yetenek_progress
  FOR EACH ROW EXECUTE FUNCTION update_cyp_updated_at();

-- RLS
ALTER TABLE candidate_yetenek_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY cyp_select_own ON candidate_yetenek_progress
  FOR SELECT TO authenticated
  USING (candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid()));


-- ═══════════════════════════════════════════════
-- 3. JOURNAL UPSERT RPC
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION upsert_studio_journal(
  p_competency_code text,
  p_question_hash text,
  p_question_text text DEFAULT NULL,
  p_role_key text DEFAULT NULL,
  p_situation text DEFAULT '',
  p_task text DEFAULT '',
  p_action text DEFAULT '',
  p_result text DEFAULT '',
  p_takeaway text DEFAULT ''
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
  v_has_content boolean;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN RETURN; END IF;

  v_has_content := (COALESCE(p_situation, '') <> '' OR COALESCE(p_task, '') <> ''
    OR COALESCE(p_action, '') <> '' OR COALESCE(p_result, '') <> '' OR COALESCE(p_takeaway, '') <> '');

  IF NOT v_has_content THEN
    -- All fields empty → delete the draft if it exists
    DELETE FROM candidate_studio_journals
      WHERE candidate_id = v_candidate_id
        AND competency_code = p_competency_code
        AND question_hash = p_question_hash;
    RETURN;
  END IF;

  INSERT INTO candidate_studio_journals (
    candidate_id, competency_code, question_hash, question_text, role_key,
    situation_text, task_text, action_text, result_text, takeaway_text,
    last_edited_at
  ) VALUES (
    v_candidate_id, p_competency_code, p_question_hash, p_question_text, p_role_key,
    p_situation, p_task, p_action, p_result, p_takeaway,
    now()
  )
  ON CONFLICT (candidate_id, competency_code, question_hash)
  DO UPDATE SET
    situation_text = EXCLUDED.situation_text,
    task_text = EXCLUDED.task_text,
    action_text = EXCLUDED.action_text,
    result_text = EXCLUDED.result_text,
    takeaway_text = EXCLUDED.takeaway_text,
    question_text = COALESCE(EXCLUDED.question_text, candidate_studio_journals.question_text),
    role_key = COALESCE(EXCLUDED.role_key, candidate_studio_journals.role_key),
    last_edited_at = now();
END;
$$;

REVOKE EXECUTE ON FUNCTION upsert_studio_journal FROM PUBLIC;
GRANT EXECUTE ON FUNCTION upsert_studio_journal TO authenticated;


-- ═══════════════════════════════════════════════
-- 4. LOAD JOURNALS FOR COMPETENCY RPC
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION get_my_journals(p_competency_code text DEFAULT NULL)
RETURNS TABLE (
  competency_code text,
  question_hash text,
  question_text text,
  situation_text text,
  task_text text,
  action_text text,
  result_text text,
  takeaway_text text,
  status text,
  last_edited_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN RETURN; END IF;

  RETURN QUERY
    SELECT j.competency_code, j.question_hash, j.question_text,
           j.situation_text, j.task_text, j.action_text, j.result_text, j.takeaway_text,
           j.status, j.last_edited_at
    FROM candidate_studio_journals j
    WHERE j.candidate_id = v_candidate_id
      AND (p_competency_code IS NULL OR j.competency_code = p_competency_code);
END;
$$;

REVOKE EXECUTE ON FUNCTION get_my_journals FROM PUBLIC;
GRANT EXECUTE ON FUNCTION get_my_journals TO authenticated;


-- ═══════════════════════════════════════════════
-- 5. YETENEK PRACTICE PROGRESS RPC
-- Records that candidate answered a question for a competency
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION record_yetenek_practice(
  p_role_key text,
  p_competency_code text,
  p_questions_answered int DEFAULT 1
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN RETURN; END IF;

  INSERT INTO candidate_yetenek_progress (
    candidate_id, role_key, competency_code, status, practice_count, questions_answered, last_practiced_at
  ) VALUES (
    v_candidate_id, p_role_key, p_competency_code, 'practiced', 1, p_questions_answered, now()
  )
  ON CONFLICT (candidate_id, role_key, competency_code)
  DO UPDATE SET
    status = CASE
      WHEN candidate_yetenek_progress.status = 'completed' THEN 'completed'
      ELSE 'practiced'
    END,
    practice_count = candidate_yetenek_progress.practice_count + 1,
    questions_answered = candidate_yetenek_progress.questions_answered + EXCLUDED.questions_answered,
    last_practiced_at = now();
END;
$$;

REVOKE EXECUTE ON FUNCTION record_yetenek_practice FROM PUBLIC;
GRANT EXECUTE ON FUNCTION record_yetenek_practice TO authenticated;


-- ═══════════════════════════════════════════════
-- 6. MARK YETENEK COMPETENCY COMPLETED RPC
-- Called when all dealt questions for a competency are answered
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION complete_yetenek_competency(
  p_role_key text,
  p_competency_code text,
  p_questions_answered int DEFAULT 0
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN RETURN; END IF;

  INSERT INTO candidate_yetenek_progress (
    candidate_id, role_key, competency_code, status, practice_count, questions_answered, last_practiced_at
  ) VALUES (
    v_candidate_id, p_role_key, p_competency_code, 'completed', 1, p_questions_answered, now()
  )
  ON CONFLICT (candidate_id, role_key, competency_code)
  DO UPDATE SET
    status = 'completed',
    practice_count = candidate_yetenek_progress.practice_count + 1,
    questions_answered = GREATEST(candidate_yetenek_progress.questions_answered, EXCLUDED.questions_answered),
    last_practiced_at = now();
END;
$$;

REVOKE EXECUTE ON FUNCTION complete_yetenek_competency FROM PUBLIC;
GRANT EXECUTE ON FUNCTION complete_yetenek_competency TO authenticated;
