-- Support Center Phase 1 — candidate-facing help articles + support tickets
-- Date: 2026-03-25
-- Type: SCHEMA + RPC + SEED + EMAIL
-- Purpose: Yardim Makaleleri, Talep Olustur, Taleplerim — candidate-side support center

-- ═══════════════════════════════════════════════
-- 1. SUPPORT ARTICLES (public-read reference table)
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS support_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  category text NOT NULL,
  title text NOT NULL,
  summary text,
  body_md text NOT NULL,
  status text NOT NULL DEFAULT 'published',
  sort_order int DEFAULT 0,
  published_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Category CHECK
ALTER TABLE support_articles ADD CONSTRAINT support_articles_category_check
  CHECK (category IN ('hesap_giris', 'profil_cv', 'mesajlar_teklifler', 'premium_odeme', 'teknik'));

ALTER TABLE support_articles ADD CONSTRAINT support_articles_status_check
  CHECK (status IN ('draft', 'published', 'archived'));

-- RLS: authenticated users can read published articles
ALTER TABLE support_articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY support_articles_read_published ON support_articles
  FOR SELECT TO authenticated
  USING (status = 'published');

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_support_articles_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_support_articles_updated_at ON support_articles;
CREATE TRIGGER trg_support_articles_updated_at
  BEFORE UPDATE ON support_articles
  FOR EACH ROW EXECUTE FUNCTION update_support_articles_updated_at();


-- ═══════════════════════════════════════════════
-- 2. SUPPORT TICKETS
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS support_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_no text UNIQUE NOT NULL,
  candidate_id bigint NOT NULL,
  user_id uuid NOT NULL,
  category text NOT NULL,
  subject text NOT NULL,
  description text NOT NULL,
  status text NOT NULL DEFAULT 'open',
  source text NOT NULL DEFAULT 'candidate_portal',
  contact_email_snapshot text,
  current_panel text,
  page_path text,
  user_agent text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE support_tickets ADD CONSTRAINT support_tickets_category_check
  CHECK (category IN ('hesap_giris', 'profil_cv', 'mesajlar_teklifler', 'premium_odeme', 'teknik'));

ALTER TABLE support_tickets ADD CONSTRAINT support_tickets_status_check
  CHECK (status IN ('open', 'in_review', 'waiting_on_candidate', 'resolved', 'closed'));

-- Indexes
CREATE INDEX IF NOT EXISTS idx_support_tickets_candidate ON support_tickets (candidate_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets (status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_created ON support_tickets (created_at DESC);

-- RLS: candidates see only own tickets, cannot change status
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY support_tickets_select_own ON support_tickets
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- No direct INSERT/UPDATE/DELETE — must go through RPC

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_support_tickets_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_support_tickets_updated_at ON support_tickets;
CREATE TRIGGER trg_support_tickets_updated_at
  BEFORE UPDATE ON support_tickets
  FOR EACH ROW EXECUTE FUNCTION update_support_tickets_updated_at();


-- ═══════════════════════════════════════════════
-- 3. SUPPORT TICKET MESSAGES
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS support_ticket_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id bigint NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  author_type text NOT NULL,
  author_user_id uuid,
  body text NOT NULL,
  visibility text NOT NULL DEFAULT 'public',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE support_ticket_messages ADD CONSTRAINT stm_author_type_check
  CHECK (author_type IN ('candidate', 'support', 'system'));

ALTER TABLE support_ticket_messages ADD CONSTRAINT stm_visibility_check
  CHECK (visibility IN ('public', 'internal'));

CREATE INDEX IF NOT EXISTS idx_stm_ticket ON support_ticket_messages (ticket_id);

-- RLS: candidates read own ticket's public messages
ALTER TABLE support_ticket_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY stm_select_own_public ON support_ticket_messages
  FOR SELECT TO authenticated
  USING (
    visibility = 'public'
    AND ticket_id IN (SELECT id FROM support_tickets WHERE user_id = auth.uid())
  );


-- ═══════════════════════════════════════════════
-- 4. TICKET CREATION RPC (atomic)
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION create_support_ticket(
  p_category text,
  p_subject text,
  p_description text,
  p_current_panel text DEFAULT NULL,
  p_page_path text DEFAULT NULL,
  p_user_agent text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_candidate_id bigint;
  v_email text;
  v_full_name text;
  v_ticket_id bigint;
  v_ticket_no text;
  v_next_seq bigint;
BEGIN
  -- Auth guard
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Oturum gereklidir.';
  END IF;

  -- Resolve candidate
  SELECT id, email, full_name INTO v_candidate_id, v_email, v_full_name
  FROM candidates WHERE user_id = v_user_id;

  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Aday profili bulunamadi.';
  END IF;

  -- Generate ticket number: HT-NNNNNN (zero-padded sequence)
  SELECT COALESCE(MAX(id), 0) + 1 INTO v_next_seq FROM support_tickets;
  v_ticket_no := 'HT-' || LPAD(v_next_seq::text, 6, '0');

  -- Insert ticket
  INSERT INTO support_tickets (
    ticket_no, candidate_id, user_id, category, subject, description,
    source, contact_email_snapshot, current_panel, page_path, user_agent
  ) VALUES (
    v_ticket_no, v_candidate_id, v_user_id, p_category, p_subject, p_description,
    'candidate_portal', v_email, p_current_panel, p_page_path, p_user_agent
  ) RETURNING id INTO v_ticket_id;

  -- Insert initial system message
  INSERT INTO support_ticket_messages (ticket_id, author_type, author_user_id, body, visibility)
  VALUES (v_ticket_id, 'candidate', v_user_id, p_description, 'public');

  -- Enqueue candidate confirmation email
  INSERT INTO email_outbox (
    email_type, recipient_email, payload, dedupe_key, source_table, source_id
  ) VALUES (
    'support_ticket_confirmation',
    v_email,
    jsonb_build_object(
      'candidate_name', COALESCE(v_full_name, ''),
      'ticket_no', v_ticket_no,
      'subject', p_subject,
      'category', p_category
    ),
    'support_confirm:' || v_ticket_id::text,
    'support_tickets',
    v_ticket_id::text
  );

  -- Enqueue internal alert to support@hellotalent.ai
  INSERT INTO email_outbox (
    email_type, recipient_email, payload, dedupe_key, source_table, source_id
  ) VALUES (
    'support_ticket_internal_alert',
    'support@hellotalent.ai',
    jsonb_build_object(
      'candidate_name', COALESCE(v_full_name, ''),
      'candidate_email', COALESCE(v_email, ''),
      'ticket_no', v_ticket_no,
      'subject', p_subject,
      'category', p_category,
      'description', p_description,
      'current_panel', COALESCE(p_current_panel, ''),
      'page_path', COALESCE(p_page_path, ''),
      'user_agent', COALESCE(p_user_agent, '')
    ),
    'support_alert:' || v_ticket_id::text,
    'support_tickets',
    v_ticket_id::text
  );

  RETURN jsonb_build_object(
    'ticket_id', v_ticket_id,
    'ticket_no', v_ticket_no
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION create_support_ticket(text, text, text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION create_support_ticket(text, text, text, text, text, text) TO authenticated;


-- ═══════════════════════════════════════════════
-- 5. EXTEND EMAIL OUTBOX CHECK CONSTRAINT
-- ═══════════════════════════════════════════════

ALTER TABLE email_outbox DROP CONSTRAINT IF EXISTS email_outbox_email_type_check;
ALTER TABLE email_outbox ADD CONSTRAINT email_outbox_email_type_check
  CHECK (email_type IN (
    'candidate_welcome',
    'employer_welcome',
    'new_message',
    'coach_invite',
    'coach_post_published',
    'coach_post_changes_requested',
    'coach_post_rejected',
    'coach_post_archived',
    'coach_post_deletion_requested',
    'coach_post_deletion_dismissed',
    'support_ticket_confirmation',
    'support_ticket_internal_alert'
  ));


-- ═══════════════════════════════════════════════
-- 6. SEED — STARTER HELP ARTICLES
-- ═══════════════════════════════════════════════

INSERT INTO support_articles (slug, category, title, summary, body_md, sort_order) VALUES

('hesabima-giris-yapamiyorum', 'hesap_giris',
 'Hesabima giris yapamiyorum',
 'Sifre sifirlama, e-posta dogrulama ve giris sorunlari icin adimlar.',
 '## Giris Sorunlari

**Sifreni mi unuttun?**
Giris sayfasindaki "Sifremi Unuttum" linkine tikla. E-posta adresine sifre sifirlama baglantisi gonderilecek.

**E-posta dogrulamasi yapmadin mi?**
Kayit oldugun e-postaya gelen dogrulama mailini kontrol et. Spam/gereksiz klasorunu de incele.

**Google veya LinkedIn ile giris yapamiyorsun?**
Kayit oldugun yontemle giris yaptigindan emin ol. Google ile kayit olduysan Google ile giris yap.

**Hala sorun mu var?**
Asagidaki "Destek Talebi Olustur" butonuyla bize ulasin.',
 1),

('cv-yukleme-sorunu', 'profil_cv',
 'CV yukleme sorunu',
 'CV dosyanizi yuklerken karsilastiginiz sorunlarin cozumleri.',
 '## CV Yukleme

**Desteklenen formatlar:** PDF, DOC, DOCX
**Maksimum boyut:** 5 MB

**Yukleme basarisiz oluyorsa:**
- Dosya boyutunun 5 MB''yi asmamasi gerekir
- PDF formatini dene (en guvenilir)
- Farkli bir tarayici kullan veya sayfayi yenile
- Dosya adinda ozel karakter varsa kaldir

**CV guncellemek icin:**
Profil Merkezi > CV bolumunden mevcut CV''ni silip yenisini yukleyebilirsin.',
 2),

('profilim-neden-gorunmuyor', 'profil_cv',
 'Profilim neden gorunmuyor',
 'Profilinizin isverenlere gorunur olmasi icin gereken adimlar.',
 '## Profil Gorunurlugu

Profilinin isverenlere gorunmesi icin:

1. **Profil tamamlanma orani en az %45 olmali** — Profil Merkezi''nde tamamlanma oranini gorebilirsin
2. **"Beni Oner" aktif olmali** — Ayarlar > Gorunurluk bolumunden kontrol et
3. **Hesabin aktif olmali** — Dondurulmus veya silme surecindeki hesaplar gorunmez

**Kontrol listesi:**
- Ad soyad, telefon ve il bilgilerin dolu mu?
- En az bir is deneyimi veya "is deneyimim yok" secimi yaptin mi?
- Tercihler bolumunde musaitlik durumunu sectin mi?

Tum bunlar tamamsa ve hala gorunmuyorsan destek talebi olustur.',
 3),

('teklifler-nasil-calisir', 'mesajlar_teklifler',
 'Teklifler nasil calisir',
 'Ozel teklifler ve isverenlerden gelen mesajlar hakkinda bilgi.',
 '## Ozel Teklifler

**Teklifler nedir?**
Isverenlerin sana ozel gonderdigi is firsatlaridir. Profilin ne kadar tamamsa o kadar fazla teklif alirsin.

**Nasil teklif alirim?**
- Profilini eksiksiz doldur
- "Beni Oner" ozelligini ac
- Aktif olarak is aradiginizi belirt

**Mesajlar ve Teklifler**
Isverenlerden gelen mesajlari Mesajlar bolumunden gorebilirsin. Her mesaja yanit verebilir, konusmayi surdurebilirsin.

**Premium teklifler**
Premium uyelikle daha fazla teklif goruntuleme hakki ve oncelikli listeleme avantaji elde edersin.',
 4),

('premium-uyelik-nasil-isler', 'premium_odeme',
 'Premium uyelik nasil isler',
 'Premium ozellikleri, fiyatlandirma ve uyelik yonetimi.',
 '## Premium Uyelik

**Premium avantajlari:**
- Kim Bakti detaylari (hangi sirket, hangi pozisyon icin inceledi)
- One Cikan Profil (arama sonuclarinda ust siralarda)
- Sinirsis Teklif Goruntuleme
- AI CV Olusturucu
- Mulakat Kocu tam erisim

**Fiyatlandirma:**
Guncel fiyatlar icin Premium bolumune goz at.

**Iptal ve iade:**
Uyeliginizi istediginiz zaman iptal edebilirsiniz. Aktif donem sonuna kadar premium avantajlariniz devam eder.',
 5),

('tarayici-uyumlulugu', 'teknik',
 'Tarayici uyumlulugu ve teknik sorunlar',
 'Desteklenen tarayicilar ve genel teknik sorunlarin cozumleri.',
 '## Teknik Bilgiler

**Desteklenen tarayicilar:**
- Chrome (onerilen)
- Safari
- Firefox
- Edge

**Sayfa duzgun yuklenmiyor:**
- Sayfayi sert yenile: Ctrl+Shift+R (Mac: Cmd+Shift+R)
- Tarayici onbellegi temizle
- Reklam engelleyicini gecici olarak kapat

**Mobil sorunlar:**
- En az iOS 15 veya Android 10 oneriyoruz
- Tarayicinin guncel surumde oldugunu kontrol et',
 6);
