-- Premium Entitlement Phase 1 — payment records + activation + webhook support
-- Date: 2026-03-27
-- Type: SCHEMA + RLS + RPC
-- Purpose:
--   1. candidate_premium_purchases — audit trail for premium activations
--   2. activate_candidate_premium — server-side idempotent entitlement activation
--   3. get_my_premium_status — candidate reads own premium state

-- ═══════════════════════════════════════════════
-- 1. CANDIDATE PREMIUM PURCHASES (audit trail)
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS candidate_premium_purchases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  plan_key text NOT NULL,
  amount_cents int NOT NULL,
  currency text NOT NULL DEFAULT 'TRY',
  provider text NOT NULL DEFAULT 'iyzico',
  provider_payment_id text,
  provider_status text,
  status text NOT NULL DEFAULT 'pending',
  duration_days int NOT NULL DEFAULT 30,
  activated_at timestamptz,
  expires_at timestamptz,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE candidate_premium_purchases ADD CONSTRAINT cpp_status_check
  CHECK (status IN ('pending', 'completed', 'failed', 'refunded'));

ALTER TABLE candidate_premium_purchases ADD CONSTRAINT cpp_plan_check
  CHECK (plan_key IN ('aylik', 'yillik', 'kariyer'));

CREATE INDEX IF NOT EXISTS idx_cpp_candidate ON candidate_premium_purchases (candidate_id);
CREATE INDEX IF NOT EXISTS idx_cpp_provider ON candidate_premium_purchases (provider_payment_id) WHERE provider_payment_id IS NOT NULL;

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_cpp_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_cpp_updated_at ON candidate_premium_purchases;
CREATE TRIGGER trg_cpp_updated_at
  BEFORE UPDATE ON candidate_premium_purchases
  FOR EACH ROW EXECUTE FUNCTION update_cpp_updated_at();

-- RLS: candidates read own purchases only
ALTER TABLE candidate_premium_purchases ENABLE ROW LEVEL SECURITY;

CREATE POLICY cpp_select_own ON candidate_premium_purchases
  FOR SELECT TO authenticated
  USING (candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid()));

-- Admin read all
DROP POLICY IF EXISTS cpp_admin_read ON candidate_premium_purchases;
CREATE POLICY cpp_admin_read ON candidate_premium_purchases
  FOR SELECT TO authenticated
  USING (is_admin());


-- ═══════════════════════════════════════════════
-- 2. ACTIVATE CANDIDATE PREMIUM (server-side, idempotent)
-- Called by: webhook Edge Function after payment confirmation, or admin manual activation.
-- Sets candidates.is_premium = true, calculates premium_until, creates purchase record.
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION activate_candidate_premium(
  p_candidate_id bigint,
  p_plan_key text,
  p_amount_cents int DEFAULT 0,
  p_provider_payment_id text DEFAULT NULL,
  p_provider_status text DEFAULT NULL,
  p_duration_days int DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_duration int;
  v_expires timestamptz;
  v_current_until timestamptz;
  v_purchase_id bigint;
BEGIN
  -- Determine duration based on plan
  IF p_duration_days IS NOT NULL THEN
    v_duration := p_duration_days;
  ELSIF p_plan_key = 'aylik' THEN
    v_duration := 30;
  ELSIF p_plan_key = 'yillik' THEN
    v_duration := 365;
  ELSIF p_plan_key = 'kariyer' THEN
    v_duration := 90;
  ELSE
    v_duration := 30;
  END IF;

  -- Calculate new expiry: extend from current premium_until if still active, else from now
  SELECT premium_until INTO v_current_until FROM candidates WHERE id = p_candidate_id;
  IF v_current_until IS NOT NULL AND v_current_until > now() THEN
    v_expires := v_current_until + (v_duration || ' days')::interval;
  ELSE
    v_expires := now() + (v_duration || ' days')::interval;
  END IF;

  -- Update candidate entitlement (THE single truth source)
  UPDATE candidates
    SET is_premium = true,
        premium_until = v_expires
    WHERE id = p_candidate_id;

  -- Create audit record
  INSERT INTO candidate_premium_purchases (
    candidate_id, plan_key, amount_cents, provider_payment_id, provider_status,
    status, duration_days, activated_at, expires_at
  ) VALUES (
    p_candidate_id, p_plan_key, p_amount_cents, p_provider_payment_id, p_provider_status,
    'completed', v_duration, now(), v_expires
  ) RETURNING id INTO v_purchase_id;

  RETURN v_purchase_id;
END;
$$;

-- This is called by Edge Function with service_role key (bypasses RLS)
-- Also callable by admin for manual activation


-- ═══════════════════════════════════════════════
-- 3. CANDIDATE-FACING PREMIUM STATUS RPC
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION get_my_premium_status()
RETURNS TABLE (
  is_premium boolean,
  premium_until timestamptz,
  plan_key text,
  days_remaining int
)
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN RETURN; END IF;

  RETURN QUERY
    SELECT
      c.is_premium,
      c.premium_until,
      (SELECT cpp.plan_key FROM candidate_premium_purchases cpp
       WHERE cpp.candidate_id = v_candidate_id AND cpp.status = 'completed'
       ORDER BY cpp.created_at DESC LIMIT 1) AS plan_key,
      CASE WHEN c.premium_until IS NOT NULL AND c.premium_until > now()
        THEN EXTRACT(DAY FROM c.premium_until - now())::int
        ELSE 0
      END AS days_remaining
    FROM candidates c
    WHERE c.id = v_candidate_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION get_my_premium_status() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION get_my_premium_status() TO authenticated;


-- ═══════════════════════════════════════════════
-- 4. CANDIDATE-FACING PURCHASE INITIATION RPC
-- Creates a pending purchase record. Returns the ID for tracking.
-- The actual payment is completed by the webhook/Edge Function.
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION initiate_premium_purchase(
  p_plan_key text,
  p_amount_cents int
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
  v_purchase_id bigint;
  v_duration int;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Aday profili bulunamadi.';
  END IF;

  IF p_plan_key = 'aylik' THEN v_duration := 30;
  ELSIF p_plan_key = 'yillik' THEN v_duration := 365;
  ELSIF p_plan_key = 'kariyer' THEN v_duration := 90;
  ELSE RAISE EXCEPTION 'Gecersiz plan.';
  END IF;

  INSERT INTO candidate_premium_purchases (
    candidate_id, plan_key, amount_cents, duration_days, status
  ) VALUES (
    v_candidate_id, p_plan_key, p_amount_cents, v_duration, 'pending'
  ) RETURNING id INTO v_purchase_id;

  RETURN v_purchase_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION initiate_premium_purchase(text, int) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION initiate_premium_purchase(text, int) TO authenticated;
