-- Studio Phase 5A — Structured AI Feedback for Yetenek Journals
-- Date: 2026-03-26
-- Type: SCHEMA + RLS + RPC
-- Purpose:
--   1. candidate_journal_feedback — persisted structured AI evaluations
--   2. request_journal_feedback RPC — creates pending feedback row
--   3. complete_journal_feedback RPC — Edge Function writes results back

-- ═══════════════════════════════════════════════
-- 1. CANDIDATE JOURNAL FEEDBACK
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS candidate_journal_feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  journal_id bigint REFERENCES candidate_studio_journals(id) ON DELETE SET NULL,
  role_key text,
  competency_code text NOT NULL,
  question_hash text NOT NULL,
  question_text text,
  model_key text NOT NULL DEFAULT 'gpt-4o-mini',
  status text NOT NULL DEFAULT 'pending',
  overall_signal text,
  score_overall int,
  strong_points jsonb,
  weak_points jsonb,
  star_review jsonb,
  improvement_actions jsonb,
  followup_questions jsonb,
  summary_text text,
  raw_response jsonb,
  error_message text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  completed_at timestamptz
);

ALTER TABLE candidate_journal_feedback ADD CONSTRAINT cjf_status_check
  CHECK (status IN ('pending', 'processing', 'completed', 'failed'));

ALTER TABLE candidate_journal_feedback ADD CONSTRAINT cjf_signal_check
  CHECK (overall_signal IS NULL OR overall_signal IN ('strong', 'mixed', 'needs_work'));

CREATE INDEX IF NOT EXISTS idx_cjf_candidate ON candidate_journal_feedback (candidate_id);
CREATE INDEX IF NOT EXISTS idx_cjf_pending ON candidate_journal_feedback (status) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_cjf_journal ON candidate_journal_feedback (candidate_id, competency_code, question_hash);

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_cjf_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_cjf_updated_at ON candidate_journal_feedback;
CREATE TRIGGER trg_cjf_updated_at
  BEFORE UPDATE ON candidate_journal_feedback
  FOR EACH ROW EXECUTE FUNCTION update_cjf_updated_at();

-- RLS: candidates read own feedback only
ALTER TABLE candidate_journal_feedback ENABLE ROW LEVEL SECURITY;

CREATE POLICY cjf_select_own ON candidate_journal_feedback
  FOR SELECT TO authenticated
  USING (candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid()));

-- No direct INSERT/UPDATE from client — must go through RPCs


-- ═══════════════════════════════════════════════
-- 2. REQUEST FEEDBACK RPC (candidate-facing)
-- Creates a pending feedback row and returns the ID.
-- Resolves journal_id from candidate_studio_journals if exists.
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION request_journal_feedback(
  p_competency_code text,
  p_question_hash text,
  p_question_text text,
  p_role_key text DEFAULT NULL,
  p_situation text DEFAULT '',
  p_task text DEFAULT '',
  p_action text DEFAULT '',
  p_result text DEFAULT '',
  p_takeaway text DEFAULT ''
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
  v_journal_id bigint;
  v_feedback_id bigint;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Aday profili bulunamadi.';
  END IF;

  -- Ensure journal draft is saved/updated first
  PERFORM upsert_studio_journal(
    p_competency_code, p_question_hash, p_question_text, p_role_key,
    p_situation, p_task, p_action, p_result, p_takeaway
  );

  -- Resolve journal_id
  SELECT id INTO v_journal_id
    FROM candidate_studio_journals
    WHERE candidate_id = v_candidate_id
      AND competency_code = p_competency_code
      AND question_hash = p_question_hash;

  -- Create pending feedback row
  INSERT INTO candidate_journal_feedback (
    candidate_id, journal_id, role_key, competency_code, question_hash,
    question_text, status
  ) VALUES (
    v_candidate_id, v_journal_id, p_role_key, p_competency_code, p_question_hash,
    p_question_text, 'pending'
  ) RETURNING id INTO v_feedback_id;

  RETURN v_feedback_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION request_journal_feedback FROM PUBLIC;
GRANT EXECUTE ON FUNCTION request_journal_feedback TO authenticated;


-- ═══════════════════════════════════════════════
-- 3. COMPLETE FEEDBACK RPC (Edge Function → DB)
-- Called by journal-feedback Edge Function after AI generation.
-- Uses service_role, not candidate auth.
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION complete_journal_feedback(
  p_feedback_id bigint,
  p_status text,
  p_overall_signal text DEFAULT NULL,
  p_score_overall int DEFAULT NULL,
  p_strong_points jsonb DEFAULT NULL,
  p_weak_points jsonb DEFAULT NULL,
  p_star_review jsonb DEFAULT NULL,
  p_improvement_actions jsonb DEFAULT NULL,
  p_followup_questions jsonb DEFAULT NULL,
  p_summary_text text DEFAULT NULL,
  p_raw_response jsonb DEFAULT NULL,
  p_error_message text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE candidate_journal_feedback SET
    status = p_status,
    overall_signal = p_overall_signal,
    score_overall = p_score_overall,
    strong_points = p_strong_points,
    weak_points = p_weak_points,
    star_review = p_star_review,
    improvement_actions = p_improvement_actions,
    followup_questions = p_followup_questions,
    summary_text = p_summary_text,
    raw_response = p_raw_response,
    error_message = p_error_message,
    completed_at = CASE WHEN p_status = 'completed' THEN now() ELSE NULL END
  WHERE id = p_feedback_id;
END;
$$;

-- This function is called by Edge Function with service_role key
-- No REVOKE needed — service_role bypasses RLS


-- ═══════════════════════════════════════════════
-- 4. GET LATEST FEEDBACK FOR A JOURNAL ENTRY (candidate-facing)
-- ═══════════════════════════════════════════════

CREATE OR REPLACE FUNCTION get_journal_feedback(
  p_competency_code text,
  p_question_hash text
)
RETURNS TABLE (
  id bigint,
  status text,
  overall_signal text,
  score_overall int,
  strong_points jsonb,
  weak_points jsonb,
  star_review jsonb,
  improvement_actions jsonb,
  followup_questions jsonb,
  summary_text text,
  error_message text,
  created_at timestamptz,
  completed_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
BEGIN
  SELECT c.id INTO v_candidate_id FROM candidates c WHERE c.user_id = auth.uid();
  IF v_candidate_id IS NULL THEN RETURN; END IF;

  RETURN QUERY
    SELECT f.id, f.status, f.overall_signal, f.score_overall,
           f.strong_points, f.weak_points, f.star_review,
           f.improvement_actions, f.followup_questions, f.summary_text,
           f.error_message, f.created_at, f.completed_at
    FROM candidate_journal_feedback f
    WHERE f.candidate_id = v_candidate_id
      AND f.competency_code = p_competency_code
      AND f.question_hash = p_question_hash
    ORDER BY f.created_at DESC
    LIMIT 1;
END;
$$;

REVOKE EXECUTE ON FUNCTION get_journal_feedback(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION get_journal_feedback(text, text) TO authenticated;
