-- Studio Modules — admin-managed learning content for Performans + HelloTalent'ten Bilgiler
-- Date: 2026-03-26
-- Type: SCHEMA + RLS + RPC + TRIGGER
-- Purpose:
--   1. studio_modules table — admin-managed content
--   2. candidate_studio_progress table — candidate progress tracking
--   3. RLS policies for candidate read + admin CRUD
--   4. Admin RPCs for module management
--   5. updated_at trigger

-- ═══════════════════════════════════════════════
-- 1. STUDIO MODULES
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS studio_modules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section text NOT NULL,
  module_type text NOT NULL DEFAULT 'article',
  slug text UNIQUE NOT NULL,
  title text NOT NULL,
  summary text,
  body_md text,
  cover_image_url text,
  cover_image_alt text,
  duration_minutes int,
  cta_label text,
  cta_url text,
  sort_order int DEFAULT 0,
  status text NOT NULL DEFAULT 'draft',
  published_at timestamptz,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE studio_modules ADD CONSTRAINT studio_modules_section_check
  CHECK (section IN ('performans', 'bilgiler'));

ALTER TABLE studio_modules ADD CONSTRAINT studio_modules_type_check
  CHECK (module_type IN ('article', 'video', 'carousel', 'lesson'));

ALTER TABLE studio_modules ADD CONSTRAINT studio_modules_status_check
  CHECK (status IN ('draft', 'published', 'archived'));

CREATE INDEX IF NOT EXISTS idx_studio_modules_section_status
  ON studio_modules (section, status, sort_order);

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_studio_modules_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_studio_modules_updated_at ON studio_modules;
CREATE TRIGGER trg_studio_modules_updated_at
  BEFORE UPDATE ON studio_modules
  FOR EACH ROW EXECUTE FUNCTION update_studio_modules_updated_at();

-- RLS
ALTER TABLE studio_modules ENABLE ROW LEVEL SECURITY;

-- Candidates can read published modules
CREATE POLICY studio_modules_read_published ON studio_modules
  FOR SELECT TO authenticated
  USING (status = 'published');

-- Admin can read all modules
DROP POLICY IF EXISTS studio_modules_admin_all ON studio_modules;
CREATE POLICY studio_modules_admin_all ON studio_modules
  FOR ALL TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());


-- ═══════════════════════════════════════════════
-- 2. CANDIDATE STUDIO PROGRESS
-- ═══════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS candidate_studio_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  module_id bigint NOT NULL REFERENCES studio_modules(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'not_started',
  progress_pct int DEFAULT 0,
  last_viewed_at timestamptz DEFAULT now(),
  completed_at timestamptz,
  created_at timestamptz DEFAULT now(),
  UNIQUE (candidate_id, module_id)
);

ALTER TABLE candidate_studio_progress ADD CONSTRAINT csp_status_check
  CHECK (status IN ('not_started', 'in_progress', 'completed'));

ALTER TABLE candidate_studio_progress ADD CONSTRAINT csp_progress_pct_check
  CHECK (progress_pct >= 0 AND progress_pct <= 100);

CREATE INDEX IF NOT EXISTS idx_csp_candidate ON candidate_studio_progress (candidate_id);

-- RLS
ALTER TABLE candidate_studio_progress ENABLE ROW LEVEL SECURITY;

-- Candidates see only own progress
CREATE POLICY csp_select_own ON candidate_studio_progress
  FOR SELECT TO authenticated
  USING (candidate_id = (SELECT id FROM candidates WHERE user_id = auth.uid()));

-- No direct INSERT/UPDATE — must go through RPC


-- ═══════════════════════════════════════════════
-- 3. ADMIN RPCs
-- ═══════════════════════════════════════════════

-- ── admin_create_studio_module ──
CREATE OR REPLACE FUNCTION admin_create_studio_module(
  p_section text,
  p_module_type text,
  p_title text,
  p_slug text,
  p_summary text DEFAULT NULL,
  p_body_md text DEFAULT NULL,
  p_cover_image_url text DEFAULT NULL,
  p_cover_image_alt text DEFAULT NULL,
  p_duration_minutes int DEFAULT NULL,
  p_cta_label text DEFAULT NULL,
  p_cta_url text DEFAULT NULL,
  p_sort_order int DEFAULT 0
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id bigint;
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Yetki hatasi: admin erisimi gereklidir.';
  END IF;

  INSERT INTO studio_modules (
    section, module_type, slug, title, summary, body_md,
    cover_image_url, cover_image_alt, duration_minutes,
    cta_label, cta_url, sort_order, created_by
  ) VALUES (
    p_section, p_module_type, p_slug, p_title, p_summary, p_body_md,
    p_cover_image_url, p_cover_image_alt, p_duration_minutes,
    p_cta_label, p_cta_url, p_sort_order, auth.uid()
  ) RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION admin_create_studio_module FROM PUBLIC;
GRANT EXECUTE ON FUNCTION admin_create_studio_module TO authenticated;


-- ── admin_update_studio_module ──
CREATE OR REPLACE FUNCTION admin_update_studio_module(
  p_id bigint,
  p_data jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Yetki hatasi: admin erisimi gereklidir.';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM studio_modules WHERE id = p_id) THEN
    RAISE EXCEPTION 'Modul bulunamadi.';
  END IF;

  UPDATE studio_modules SET
    section          = COALESCE(p_data->>'section', section),
    module_type      = COALESCE(p_data->>'module_type', module_type),
    title            = COALESCE(p_data->>'title', title),
    slug             = COALESCE(p_data->>'slug', slug),
    summary          = CASE WHEN p_data ? 'summary' THEN p_data->>'summary' ELSE summary END,
    body_md          = CASE WHEN p_data ? 'body_md' THEN p_data->>'body_md' ELSE body_md END,
    cover_image_url  = CASE WHEN p_data ? 'cover_image_url' THEN p_data->>'cover_image_url' ELSE cover_image_url END,
    cover_image_alt  = CASE WHEN p_data ? 'cover_image_alt' THEN p_data->>'cover_image_alt' ELSE cover_image_alt END,
    duration_minutes = CASE WHEN p_data ? 'duration_minutes' THEN (p_data->>'duration_minutes')::int ELSE duration_minutes END,
    cta_label        = CASE WHEN p_data ? 'cta_label' THEN p_data->>'cta_label' ELSE cta_label END,
    cta_url          = CASE WHEN p_data ? 'cta_url' THEN p_data->>'cta_url' ELSE cta_url END,
    sort_order       = CASE WHEN p_data ? 'sort_order' THEN (p_data->>'sort_order')::int ELSE sort_order END
  WHERE id = p_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION admin_update_studio_module(bigint, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION admin_update_studio_module(bigint, jsonb) TO authenticated;


-- ── admin_publish_studio_module ──
CREATE OR REPLACE FUNCTION admin_publish_studio_module(p_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Yetki hatasi: admin erisimi gereklidir.';
  END IF;

  UPDATE studio_modules
    SET status = 'published', published_at = now()
    WHERE id = p_id AND status IN ('draft', 'archived');

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Modul bulunamadi veya zaten yayinda.';
  END IF;
END;
$$;

REVOKE EXECUTE ON FUNCTION admin_publish_studio_module(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION admin_publish_studio_module(bigint) TO authenticated;


-- ── admin_archive_studio_module ──
CREATE OR REPLACE FUNCTION admin_archive_studio_module(p_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Yetki hatasi: admin erisimi gereklidir.';
  END IF;

  UPDATE studio_modules
    SET status = 'archived'
    WHERE id = p_id AND status = 'published';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Modul bulunamadi veya yayinda degil.';
  END IF;
END;
$$;

REVOKE EXECUTE ON FUNCTION admin_archive_studio_module(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION admin_archive_studio_module(bigint) TO authenticated;


-- ═══════════════════════════════════════════════
-- 4. CANDIDATE RPCs
-- ═══════════════════════════════════════════════

-- ── mark_studio_module_viewed ──
-- Upserts progress row: creates if not exists, updates last_viewed_at + status
CREATE OR REPLACE FUNCTION mark_studio_module_viewed(p_module_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Aday profili bulunamadi.';
  END IF;

  -- Only track published modules
  IF NOT EXISTS (SELECT 1 FROM studio_modules WHERE id = p_module_id AND status = 'published') THEN
    RETURN; -- silently skip unpublished
  END IF;

  INSERT INTO candidate_studio_progress (candidate_id, module_id, status, last_viewed_at)
  VALUES (v_candidate_id, p_module_id, 'in_progress', now())
  ON CONFLICT (candidate_id, module_id)
  DO UPDATE SET last_viewed_at = now(),
    status = CASE WHEN candidate_studio_progress.status = 'not_started' THEN 'in_progress' ELSE candidate_studio_progress.status END;
END;
$$;

REVOKE EXECUTE ON FUNCTION mark_studio_module_viewed(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION mark_studio_module_viewed(bigint) TO authenticated;


-- ── complete_studio_module ──
CREATE OR REPLACE FUNCTION complete_studio_module(p_module_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_candidate_id bigint;
BEGIN
  SELECT id INTO v_candidate_id FROM candidates WHERE user_id = auth.uid();
  IF v_candidate_id IS NULL THEN
    RAISE EXCEPTION 'Aday profili bulunamadi.';
  END IF;

  INSERT INTO candidate_studio_progress (candidate_id, module_id, status, progress_pct, completed_at)
  VALUES (v_candidate_id, p_module_id, 'completed', 100, now())
  ON CONFLICT (candidate_id, module_id)
  DO UPDATE SET status = 'completed', progress_pct = 100, completed_at = now(), last_viewed_at = now();
END;
$$;

REVOKE EXECUTE ON FUNCTION complete_studio_module(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION complete_studio_module(bigint) TO authenticated;
